# Catálogo de proyectables y de material imprimible (lo usan la web y el documento 08).

PROYECTABLES = [
    # id, icono, nombre, cursos, descripción, [(reto, etiqueta)]
    ("cuadricula", "🤖", "Robot en la cuadrícula", "1º-3º · repaso 4º-6º", "Programa a un robot con tarjetas de flechas y REPITE en un tablero. Incluye mapas del tesoro, cazabichos y retos de figuras. El repaso para 4º-6º trabaja algoritmos con coordenadas: ¿dónde acaba el robot? y cazabichos.",
     [("mapa1", "Mapa 1"), ("mapa2", "Mapa 2"), ("mapa3", "Mapa 3"), ("mapa4", "Mapa 4"), ("mapa5", "Mapa 5"), ("mapa6", "Mapa 6"), ("bicho1", "Cazabichos 1"), ("bicho2", "Cazabichos 2"), ("bicho3", "Cazabichos 3"), ("bicho4", "Cazabichos 4"), ("escalera", "La escalera"), ("cuadrado", "El cuadrado"), ("absoluto", "Modo fácil"), ("libre", "Tablero libre"), ("grande", "Tablero 7×7"), ("repaso", "Repaso 4º-6º")]),
    ("secuencias", "🧩", "Ordena la secuencia", "1º-2º · repaso 4º-6º", "Viñetas con pictogramas de rutinas que solo tienen un orden posible. Se ordenan tocándolas en la pizarra. El repaso para 4º-6º ordena algoritmos de su día a día (la micro:bit, una suma, la media) en los que a veces vale más de un orden.",
     [("manos", "Lavarse las manos"), ("dientes", "Lavarse los dientes"), ("zapatos", "Ponerse los zapatos"), ("tostada", "Hacer una tostada"), ("semilla", "Plantar una semilla"), ("calle", "Cruzar la calle"), ("manos6", "Lavarse las manos en 6 pasos"), ("repaso", "Repaso 4º-6º")]),
    ("patrones", "🔺", "Patrones", "1º-3º · repaso 4º-6º", "Patrones de figuras para continuar, patrones que crecen y patrones con bicho. El repaso para 4º-6º: figuras que crecen (¿cuántos tendrá la figura 10?), series de números y series con bicho.",
     [("ab", "AB"), ("aab", "AAB"), ("abb", "ABB"), ("aabb", "AABB"), ("abc", "ABC"), ("abcd", "ABCD"), ("crece", "Que crece"), ("bicho", "Con bicho"), ("repaso", "Repaso 4º-6º")]),
    ("bucles", "🔁", "Bucles: largo o corto", "1º-4º · repaso 4º-6º", "Compara un programa largo con su versión con REPITE y cuenta las tarjetas que se ahorran. El repaso para 4º-6º: repetir, un bucle dentro de otro y repetir hasta que, con los bloques de Scratch.",
     [("palmadas", "Palmadas"), ("escalera", "Escalera"), ("cuadrado", "Cuadrado"), ("baile", "Baile"), ("repaso", "Repaso 4º-6º")]),
    ("semaforo", "🚦", "Semáforo de peatones: si… entonces", "2º-4º · repaso 4º-6º", "El semáforo de peatones (muñeco rojo y verde) para trabajar las reglas SI… ENTONCES y SI… SI NO. El repaso para 4º-6º usa sensores de la micro:bit y juegos de Scratch: si no, tres caminos, «y» y «o».",
     [("", "SI… ENTONCES"), ("sino", "SI… SI NO"), ("repaso", "Repaso 4º-6º")]),
    ("clasificador", "🗂️", "Clasificador y regla secreta", "1º-3º · repaso 4º-6º", "Clasificar objetos por color, tipo o tamaño, y adivinar la regla secreta de la máquina. El repaso para 4º-6º usa números del 1 al 30: reglas con «y», «o» y «no», y un árbol de decisión.",
     [("", "Por tipo"), ("color", "Por color"), ("tam", "Por tamaño"), ("secreta", "Regla secreta"), ("repaso", "Repaso 4º-6º")]),
    ("animales", "🐾", "¿Qué animal soy?", "1º-3º", "El ordenador piensa uno de 8 animales y la clase lo descubre eligiendo entre 5 preguntas de sí o no.", [("", "Jugar")]),
    ("votaciones", "📊", "Votaciones y gráfico", "1º-6º", "Encuestas con gráfico de barras en directo, un dado para estudiar frecuencias y el dado de la clase, que compara las tiradas de verdad con 1000 del ordenador.",
     [("mascotas", "Mascotas"), ("juegos", "Juegos"), ("fruta", "Frutas"), ("dado", "Dado"), ("clase", "Dado de la clase"), ("mis", "Mis opciones")]),
    ("diagrama", "🔷", "Diagramas de flujo paso a paso", "3º-4º", "Recorre un diagrama de flujo paso a paso decidiendo en cada rombo.",
     [("calle", "Cruzar la calle"), ("planta", "Regar una planta"), ("par", "Par o impar"), ("adivina", "Adivina el número")]),
    ("adivina", "", "Adivina el número", "3º-6º", "El juego de las pistas «es más grande» y «es más pequeño» (4º S5): el ordenador piensa y la recta numérica tacha lo descartado, la clase piensa y el ordenador adivina preguntando por la mitad, y cuántas preguntas hacen falta (del 1 al 100, 7; del 1 al millón, 20).",
     [("", "El ordenador piensa"), ("clase", "Piensa la clase"), ("cuantas", "¿Cuántas preguntas?")]),
    ("poligonos", "⬡", "Polígonos", "3º-4º", "Cuántos lados, cuánto girar: el programa que dibuja cada polígono y el rosetón.",
     [("", "Polígonos"), ("roseton", "Rosetón")]),
    ("variables", "📦", "Variables", "3º-6º", "Cajas con nombre y los bloques que las cambian, con los nombres de Scratch o de MakeCode: dar el valor frente a sumar, un juego de cálculo con puntos y vidas, programas para predecir cuánto vale una variable al final y la mascota virtual.",
     [("", "La caja"), ("juego", "Juego de cálculo"), ("traza", "¿Cuánto vale al final?"), ("mascota", "La mascota (MakeCode)")]),
    ("coordenadas", "🐱", "Coordenadas del escenario", "3º-6º", "El escenario de Scratch con sus ejes x e y: explorar los puntos, mover al gato con bloques (ir a, sumar a x, dar a x el valor), leer y colocar puntos, y dibujar figuras uniendo puntos.",
     [("", "Explorar"), ("bloques", "Con bloques"), ("donde", "¿Dónde está?"), ("dibujar", "Dibujar con «ir a»")]),
    ("vistas", "", "Cubos y vistas", "4º-6º", "Figuras de cubos y sus vistas de frente, desde arriba y de lado, como en el cubo de vistas de Tinkercad: construir, elegir la vista correcta y contar los cubos, también los que no se ven.",
     [("", "Construir"), ("cual", "¿Qué vista es?"), ("cuantos", "¿Cuántos cubos?")]),
    ("circuito", "💡", "¿Conduce la electricidad?", "3º-4º", "Un circuito con pila y bombilla: elige un objeto, vota y prueba si se enciende.", [("", "Abrir")]),
    ("leds", "🟥", "Matriz de LED de la micro:bit", "5º-6º", "La pantalla de 5 × 5 luces para dibujar iconos y entender las coordenadas.", [("corazon", "Corazón"), ("sonrisa", "Sonrisa"), ("flecha", "Flecha"), ("si", "Sí"), ("no", "No")]),
    ("umbral", "🌗", "Sensor y umbral", "5º-6º", "Qué mide el sensor, dónde está el umbral y qué decide el programa.", [("", "Luz"), ("temp", "Temperatura")]),
    ("mensajes", "", "Mensajes: enviar y recibir", "4º-6º", "Un mensaje llega a todos, pero solo reacciona quien tiene «al recibir» (Scratch, 4º S13); y la radio de la micro:bit: solo se oyen las placas del mismo grupo (6º S14).",
     [("", "En Scratch"), ("radio", "Radio de la micro:bit")]),
    ("velocidad", "🚙", "Velocidad × tiempo", "5º-6º", "Predice cuánto avanza el robot Nezha según la velocidad y el tiempo.", [("", "Abrir")]),
    ("sesgo", "🍎", "Entrena a la máquina", "5º-6º", "Una máquina que aprende qué es una manzana a partir de ejemplos. Con ejemplos poco variados aprende mal: eso es un sesgo. Sin cámara.", [("", "Abrir")]),
    ("verdad", "🔍", "¿Puede pasar de verdad? · ¿Verdad, bulo o IA?", "1º-2º (reserva) · 5º-6º", "Tarjetas para votar y comprobar, con la explicación de cada una.", [("fantasia", "¿Puede pasar de verdad?"), ("bulos", "Verdad, bulo o IA")]),
    ("contrasenas", "🔐", "Contraseñas seguras", "3º-6º", "Medidor de seguridad y juego de «¿cuál es más segura?».", [("", "Abrir")]),
    ("temporizador", "⏱️", "Temporizador de sesión", "1º-6º", "Cuenta atrás de 45 minutos con la fase de la sesión en grande.", [("semanal", "Semanal"), ("quincenal", "Quincenal")]),
    ("cifrado", "🔡", "Código secreto", "2º-6º", "Cifra y descifra mensajes con números o símbolos.", [("", "Abrir")]),
    ("beebot", "🐝", "Bee-Bot interactivo", "1º-2º", "La abeja robot con su botonera real: las órdenes se guardan en una memoria escondida y se ejecutan con GO. Funciona igual que Tale-Bot. Tapetes de números, abecedario y granja.",
     [("numeros", "Camino numérico"), ("letras", "Abecedario"), ("granja", "La granja"), ("cuadricula", "Cuadrícula libre")]),
    ("flota", "🚢", "Hundir la flota", "1º-6º", "Coordenadas jugando: la clase contra el ordenador o dos equipos, cada uno con su flota. Con letra y número (B3) o en el plano con ejes (x, y), también con negativos.",
     [("", "5 × 5 · letra y número"), ("grande", "8 × 8 · letra y número"), ("xy", "Plano (x, y) · de 0 a 7"), ("xyneg", "Plano (x, y) · de −4 a 4")]),
    ("pixelart", "🎨", "Píxel art con código", "1º-4º", "Dibujos secretos descritos con números fila a fila, y dibujo libre que genera su código. Así guarda un ordenador una imagen.",
     [("flecha", "Flecha 5 × 5"), ("corazon", "Corazón"), ("casa", "Casa"), ("robot", "Robot"), ("pez", "Pez"), ("libre", "Pintar y ver el código")]),
    ("laberinto", "🧭", "Laberinto de bloques", "2º-6º", "Seis niveles con bloques tipo Scratch: avanzar, girar, repetir hasta la meta y «si hay camino».",
     [("1", "Nivel 1"), ("2", "Nivel 2 · girar"), ("3", "Nivel 3 · repetir"), ("4", "Nivel 4 · escalera"), ("5", "Nivel 5 · si"), ("6", "Nivel 6 · si… si no")]),
    ("binario", "🃏", "Cartas binarias", "3º-6º", "Cartas de 1, 2, 4, 8 y 16 puntos para descubrir cómo cuentan los ordenadores con unos y ceros.", [("3", "3 cartas"), ("4", "4 cartas"), ("5", "5 cartas")]),
    ("simon", "🎵", "Simón: secuencias", "1º-3º", "Secuencias de colores, flechas y sonidos que crecen en cada ronda. Memoria y orden.", [("", "Jugar")]),
    ("balanza", "⚖️", "Ordenar con la balanza", "3º-6º", "Cajas con pesos ocultos que se ordenan comparándolas de dos en dos: un algoritmo de ordenación.", [("4", "4 cajas"), ("6", "6 cajas"), ("8", "8 cajas")]),
    ("paridad", "🔮", "Magia de la paridad", "4º-6º", "El truco de magia que adivina qué carta se ha girado. Así detectan errores los ordenadores.", [("", "Jugar")]),
    ("quiensale", "🎲", "¿Quién sale? y marcador", "1º-6º", "Elige al azar quién sale a la pizarra, sin repetir, y lleva los puntos de los equipos.", [("", "Abrir")]),
]

EXTERNAS = [
    ("Blockly Games", "https://blockly.games/?lang=es", "3º-6º", "Juegos de Google en español y sin registro: laberinto, pájaro, tortuga. Muy buenos para hacerlos en la pizarra con toda la clase."),
    ("Quick, Draw!", "https://quickdraw.withgoogle.com/", "5º-6º", "Una IA intenta adivinar lo que dibujáis en 20 segundos. Salen alumnos a dibujar en la pizarra. Ideal para hablar de cómo aprende una IA."),
    ("AI for Oceans (Code.org)", "https://code.org/oceans", "5º-6º", "Entrenar una IA para separar peces de basura: datos de entrenamiento y sesgo. Se puede hacer en la pizarra, en español."),
    ("Hora del Código: laberinto clásico", "https://studio.code.org/es/hoc/1", "3º-6º", "20 niveles de laberinto con bloques, en español y sin cuenta. Se puede hacer en la pizarra con toda la clase."),
    ("CS Unplugged", "https://www.csunplugged.org/es/", "1º-6º", "Actividades de informática sin ordenador, con guía para el docente."),
    ("Teachable Machine", "https://teachablemachine.withgoogle.com/", "3º-6º", "Entrenar un modelo de IA con la cámara (demostración del docente, sin caras)."),
]


# Retos para las tablets del alumnado (web/tablet/): se abren con un QR que el docente proyecta.
# id, nombre, cursos, qué hacen, niveles
TABLET = [
    ("robot", "Programa al robot", "3º-4º", "Llevar al robot a la estrella con avanzar, girar y repetir. Con menos bloques, más estrellas.",
     ["Niveles 1 a 3: secuencias y giros.", "Niveles 4 a 10: repetir. Para las 3 estrellas hay que usarlo."]),
    ("coordenadas", "Coordenadas", "3º-6º", "Tocar el punto que se pide o escribir dónde está la estrella.",
     ["Niveles 1 y 2: cuadrícula del 0 al 6 (3º y 4º).", "Niveles 3 y 4: con negativos, del −5 al 5 (5º y 6º).", "Nivel 5: el escenario de Scratch, con 15 pasos de margen."]),
    ("variables", "¿Cuánto vale?", "4º-6º", "Leer un programa corto, con bloques de Scratch o de MakeCode, y decir cuánto vale la variable al final. Si se fallan, ven la tabla paso a paso.",
     ["Nivel 1: dar el valor y sumar.", "Nivel 2: «dar el valor» borra lo que había.", "Nivel 3: con repetir (sumar varias veces es multiplicar).", "Nivel 4: dos variables."]),
    ("cubos", "Cubos y vistas", "4º-6º", "Contar los cubos de una figura, también los que no se ven, y elegir su vista de frente, desde arriba o de lado.",
     ["Nivel 1: figuras pequeñas (3 × 3, dos pisos).", "Nivel 2: figuras de hasta cuatro pisos.", "Nivel 3: ¿qué vista es?"]),
    ("adivina", "Adivina el número", "3º-6º", "Encontrar el número con las pistas «más grande» y «más pequeño». La recta enseña dónde puede estar todavía.",
     ["Nivel 1: del 1 al 20 (3 estrellas con 5 intentos o menos).", "Nivel 2: del 1 al 100 (con 7 o menos).", "Nivel 3: del 1 al 1000 (con 10 o menos)."]),
]
