# Catálogo de proyectables y de material imprimible (lo usan la web y el documento 08).

PROYECTABLES = [
    # id, icono, nombre, cursos, descripción, [(reto, etiqueta)]
    ("cuadricula", "🤖", "Robot en la cuadrícula", "1º-3º · repaso 4º-6º", "Programa a un robot con tarjetas de flechas y REPITE en un tablero. Incluye mapas del tesoro, cazabichos y retos de figuras. El repaso para 4º-6º trabaja algoritmos con coordenadas: ¿dónde acaba el robot? y cazabichos.",
     [("mapa1", "Mapa 1"), ("mapa2", "Mapa 2"), ("mapa3", "Mapa 3"), ("mapa4", "Mapa 4"), ("mapa5", "Mapa 5"), ("mapa6", "Mapa 6"), ("bicho1", "Cazabichos 1"), ("bicho2", "Cazabichos 2"), ("bicho3", "Cazabichos 3"), ("bicho4", "Cazabichos 4"), ("escalera", "La escalera"), ("cuadrado", "El cuadrado"), ("absoluto", "Modo fácil"), ("libre", "Tablero libre"), ("grande", "Tablero 7×7"), ("repaso", "Repaso 4º-6º")]),
    ("secuencias", "🧩", "Ordena la secuencia", "1º-2º · repaso 4º-6º", "Viñetas con pictogramas de rutinas que solo tienen un orden posible. Se ordenan tocándolas en la pizarra. El repaso para 4º-6º ordena algoritmos de su día a día (la micro:bit, una suma, la media) en los que a veces vale más de un orden.",
     [("manos", "Lavarse las manos"), ("dientes", "Lavarse los dientes"), ("zapatos", "Ponerse los zapatos"), ("tostada", "Hacer una tostada"), ("semilla", "Plantar una semilla"), ("calle", "Cruzar la calle"), ("manos6", "Lavarse las manos en 6 pasos"), ("repaso", "Repaso 4º-6º")]),
    ("patrones", "🔺", "Patrones", "1º-3º · repaso 4º-6º", "Patrones de figuras para continuar, patrones que crecen y patrones con bicho. El repaso para 4º-6º: figuras que crecen (¿cuántos tendrá la figura 10?), series de números y series con bicho.",
     [("ab", "AB"), ("aab", "AAB"), ("abb", "ABB"), ("aabb", "AABB"), ("abc", "ABC"), ("abcd", "ABCD"), ("crece", "Que crece"), ("bicho", "Con bicho"), ("repaso", "Repaso 4º-6º")]),
    ("bucles", "🔁", "Bucles: largo o corto", "1º-4º · repaso 4º-6º", "Compara un programa largo con su versión con REPITE y cuenta las tarjetas que se ahorran. El repaso para 4º-6º: repetir, un bucle dentro de otro y repetir hasta que, con los bloques de Scratch.",
     [("palmadas", "Palmadas"), ("escalera", "Escalera"), ("cuadrado", "Cuadrado"), ("baile", "Baile"), ("repaso", "Repaso 4º-6º")]),
    ("semaforo", "🚦", "Semáforo de peatones: si… entonces", "2º-4º · repaso 4º-6º", "El semáforo de peatones (muñeco rojo y verde) para trabajar las reglas SI… ENTONCES y SI… SI NO. El repaso para 4º-6º usa sensores de la micro:bit y juegos de Scratch: si no, tres caminos, «y» y «o».",
     [("", "SI… ENTONCES"), ("sino", "SI… SI NO"), ("repaso", "Repaso 4º-6º")]),
    ("clasificador", "🗂️", "Clasificador y regla secreta", "1º-3º · repaso 4º-6º", "Clasificar objetos por color, tipo o tamaño, y adivinar la regla secreta de la máquina. El repaso para 4º-6º usa números del 1 al 30: reglas con «y», «o» y «no», y un árbol de decisión.",
     [("", "Por tipo"), ("color", "Por color"), ("tam", "Por tamaño"), ("secreta", "Regla secreta"), ("repaso", "Repaso 4º-6º")]),
    ("animales", "🐾", "¿Qué animal soy?", "1º-3º", "El ordenador piensa uno de 8 animales y la clase lo descubre eligiendo entre 5 preguntas de sí o no.", [("", "Jugar")]),
    ("votaciones", "📊", "Votaciones y gráfico", "1º-6º", "Encuestas con gráfico de barras en directo, un dado para estudiar frecuencias y el dado de la clase, que compara las tiradas de verdad con 1000 del ordenador.",
     [("mascotas", "Mascotas"), ("juegos", "Juegos"), ("fruta", "Frutas"), ("dado", "Dado"), ("clase", "Dado de la clase"), ("mis", "Mis opciones")]),
    ("diagrama", "🔷", "Diagramas de flujo paso a paso", "3º-4º", "Recorre un diagrama de flujo paso a paso decidiendo en cada rombo.",
     [("calle", "Cruzar la calle"), ("planta", "Regar una planta"), ("par", "Par o impar"), ("adivina", "Adivina el número")]),
    ("adivina", "", "Adivina el número", "3º-6º", "El juego de las pistas «es más grande» y «es más pequeño» (4º S5): el ordenador piensa y la recta numérica tacha lo descartado, la clase piensa y el ordenador adivina preguntando por la mitad, y cuántas preguntas hacen falta (del 1 al 100, 7; del 1 al millón, 20).",
     [("", "El ordenador piensa"), ("clase", "Piensa la clase"), ("cuantas", "¿Cuántas preguntas?")]),
    ("poligonos", "⬡", "Polígonos", "3º-4º", "Cuántos lados, cuánto girar: el programa que dibuja cada polígono y el rosetón.",
     [("", "Polígonos"), ("roseton", "Rosetón")]),
    ("variables", "📦", "Variables", "3º-6º", "Cajas con nombre y los bloques que las cambian, con los nombres de Scratch o de MakeCode: dar el valor frente a sumar, un juego de cálculo con puntos y vidas, programas para predecir cuánto vale una variable al final y la mascota virtual.",
     [("", "La caja"), ("juego", "Juego de cálculo"), ("traza", "¿Cuánto vale al final?"), ("mascota", "La mascota (MakeCode)")]),
    ("coordenadas", "🐱", "Coordenadas del escenario", "3º-6º", "El escenario de Scratch con sus ejes x e y: explorar los puntos, mover al gato con bloques (ir a, sumar a x, dar a x el valor), leer y colocar puntos, y dibujar figuras uniendo puntos.",
     [("", "Explorar"), ("bloques", "Con bloques"), ("donde", "¿Dónde está?"), ("dibujar", "Dibujar con «ir a»")]),
    ("vistas", "", "Cubos y vistas", "4º-6º", "Figuras de cubos y sus vistas de frente, desde arriba y de lado, como en el cubo de vistas de Tinkercad: construir, elegir la vista correcta y contar los cubos, también los que no se ven.",
     [("", "Construir"), ("cual", "¿Qué vista es?"), ("cuantos", "¿Cuántos cubos?")]),
    ("circuito", "💡", "¿Conduce la electricidad?", "3º-4º", "Un circuito con pila y bombilla: elige un objeto, vota y prueba si se enciende.", [("", "Abrir")]),
    ("leds", "🟥", "Matriz de LED de la micro:bit", "5º-6º", "La pantalla de 5 × 5 luces para dibujar iconos y entender las coordenadas.", [("corazon", "Corazón"), ("sonrisa", "Sonrisa"), ("flecha", "Flecha"), ("si", "Sí"), ("no", "No")]),
    ("umbral", "🌗", "Sensor y umbral", "5º-6º", "Qué mide el sensor, dónde está el umbral y qué decide el programa.", [("", "Luz"), ("temp", "Temperatura")]),
    ("mensajes", "", "Mensajes: enviar y recibir", "4º-6º", "Un mensaje llega a todos, pero solo reacciona quien tiene «al recibir» (Scratch, 4º S13); y la radio de la micro:bit: solo se oyen las placas del mismo grupo (6º S14).",
     [("", "En Scratch"), ("radio", "Radio de la micro:bit")]),
    ("velocidad", "🚙", "Velocidad × tiempo", "5º-6º", "Predice cuánto avanza el robot Nezha según la velocidad y el tiempo.", [("", "Abrir")]),
    ("sesgo", "🍎", "Entrena a la máquina", "5º-6º", "Una máquina que aprende qué es una manzana a partir de ejemplos. Con ejemplos poco variados aprende mal: eso es un sesgo. Sin cámara.", [("", "Abrir")]),
    ("verdad", "🔍", "¿Puede pasar de verdad? · ¿Verdad, bulo o IA?", "1º-2º (reserva) · 5º-6º", "Tarjetas para votar y comprobar, con la explicación de cada una.", [("fantasia", "¿Puede pasar de verdad?"), ("bulos", "Verdad, bulo o IA")]),
    ("contrasenas", "🔐", "Contraseñas seguras", "3º-6º", "Medidor de seguridad y juego de «¿cuál es más segura?».", [("", "Abrir")]),
    ("temporizador", "⏱️", "Temporizador de sesión", "1º-6º", "Cuenta atrás de 45 minutos con la fase de la sesión en grande.", [("semanal", "Semanal"), ("quincenal", "Quincenal")]),
    ("cifrado", "🔡", "Código secreto", "2º-6º", "Cifra y descifra mensajes con números o símbolos.", [("", "Abrir")]),
    ("beebot", "🐝", "Bee-Bot interactivo", "1º-2º", "La abeja robot con su botonera real: las órdenes se guardan en una memoria escondida y se ejecutan con GO. Funciona igual que Tale-Bot. Tapetes de números, abecedario y granja.",
     [("numeros", "Camino numérico"), ("letras", "Abecedario"), ("granja", "La granja"), ("cuadricula", "Cuadrícula libre")]),
    ("flota", "🚢", "Hundir la flota", "1º-6º", "Coordenadas jugando: la clase contra el ordenador o dos equipos, cada uno con su flota. Con letra y número (B3) o en el plano con ejes (x, y), también con negativos.",
     [("", "5 × 5 · letra y número"), ("grande", "8 × 8 · letra y número"), ("xy", "Plano (x, y) · de 0 a 7"), ("xyneg", "Plano (x, y) · de −4 a 4")]),
    ("pixelart", "🎨", "Píxel art con código", "1º-4º", "Dibujos secretos descritos con números fila a fila, y dibujo libre que genera su código. Así guarda un ordenador una imagen.",
     [("flecha", "Flecha 5 × 5"), ("corazon", "Corazón"), ("casa", "Casa"), ("robot", "Robot"), ("pez", "Pez"), ("libre", "Pintar y ver el código")]),
    ("laberinto", "🧭", "Laberinto de bloques", "2º-6º", "Seis niveles con bloques tipo Scratch: avanzar, girar, repetir hasta la meta y «si hay camino».",
     [("1", "Nivel 1"), ("2", "Nivel 2 · girar"), ("3", "Nivel 3 · repetir"), ("4", "Nivel 4 · escalera"), ("5", "Nivel 5 · si"), ("6", "Nivel 6 · si… si no")]),
    ("binario", "🃏", "Cartas binarias", "3º-6º", "Cartas de 1, 2, 4, 8 y 16 puntos para descubrir cómo cuentan los ordenadores con unos y ceros.", [("3", "3 cartas"), ("4", "4 cartas"), ("5", "5 cartas")]),
    ("simon", "🎵", "Simón: secuencias", "1º-3º", "Secuencias de colores, flechas y sonidos que crecen en cada ronda. Memoria y orden.", [("", "Jugar")]),
    ("balanza", "⚖️", "Ordenar con la balanza", "3º-6º", "Cajas con pesos ocultos que se ordenan comparándolas de dos en dos: un algoritmo de ordenación.", [("4", "4 cajas"), ("6", "6 cajas"), ("8", "8 cajas")]),
    ("paridad", "🔮", "Magia de la paridad", "4º-6º", "El truco de magia que adivina qué carta se ha girado. Así detectan errores los ordenadores.", [("", "Jugar")]),
    ("quiensale", "🎲", "¿Quién sale? y marcador", "1º-6º", "Elige al azar quién sale a la pizarra, sin repetir, y lleva los puntos de los equipos.", [("", "Abrir")]),
]

EXTERNAS = [
    ("Blockly Games", "https://blockly.games/?lang=es", "3º-6º", "Juegos de Google en español y sin registro: laberinto, pájaro, tortuga. Muy buenos para hacerlos en la pizarra con toda la clase."),
    ("Quick, Draw!", "https://quickdraw.withgoogle.com/", "5º-6º", "Una IA intenta adivinar lo que dibujáis en 20 segundos. Salen alumnos a dibujar en la pizarra. Ideal para hablar de cómo aprende una IA."),
    ("AI for Oceans (Code.org)", "https://code.org/oceans", "5º-6º", "Entrenar una IA para separar peces de basura: datos de entrenamiento y sesgo. Se puede hacer en la pizarra, en español."),
    ("Hora del Código: laberinto clásico", "https://studio.code.org/es/hoc/1", "3º-6º", "20 niveles de laberinto con bloques, en español y sin cuenta. Se puede hacer en la pizarra con toda la clase."),
    ("CS Unplugged", "https://www.csunplugged.org/es/", "1º-6º", "Actividades de informática sin ordenador, con guía para el docente."),
    ("Teachable Machine", "https://teachablemachine.withgoogle.com/", "3º-6º", "Entrenar un modelo de IA con la cámara (demostración del docente, sin caras)."),
]


# Retos para las tablets y los portátiles del alumnado (web/tablet/): se abren con un QR o con el icono.
# id, nombre, cursos, qué hacen, niveles (cada uno con el curso desde el que se recomienda; se puede empezar por cualquiera)
TABLET = [
    ("robot", "Programa al robot", "3º-4º", "Llevar al robot a la estrella con avanzar, girar y repetir. Con menos bloques, más estrellas.",
     ["Niveles 1 a 3 (desde 3º): secuencias y giros.", "Niveles 4 a 8 (3º y 4º): repetir. Para las 3 estrellas hay que usarlo.", "Niveles 9 y 10 (4º): el robot empieza mirando hacia abajo, y dos repetir seguidos."]),
    ("coordenadas", "Coordenadas", "3º-6º", "Tocar el punto que se pide o escribir dónde está la estrella.",
     ["Niveles 1 y 2 (3º y 4º): cuadrícula del 0 al 6.", "Niveles 3 y 4 (5º y 6º): con negativos, del −5 al 5.", "Nivel 5 (desde 4º): el escenario de Scratch, con 15 pasos de margen."]),
    ("variables", "¿Cuánto vale?", "3º-6º", "Leer un programa corto, con bloques de Scratch o de MakeCode, y decir cuánto vale la variable al final. Si se fallan dos veces, ven la tabla paso a paso.",
     ["Nivel 1 (desde 3º): dar el valor y sumar.", "Nivel 2 (desde 4º): «dar el valor» borra lo que había; sumar −2 es quitar 2.", "Nivel 3 (desde 4º): con repetir (sumar varias veces es multiplicar).", "Nivel 4 (5º y 6º): dos variables."]),
    ("cubos", "Cubos y vistas", "4º-6º", "Contar los cubos de una figura, también los que no se ven, y elegir su vista de frente, desde arriba o de lado.",
     ["Nivel 1 (desde 4º): figuras pequeñas (3 × 3, dos pisos).", "Nivel 2 (5º y 6º): figuras de hasta cuatro pisos.", "Nivel 3 (5º y 6º): ¿qué vista es?"]),
    ("adivina", "Adivina el número", "3º-6º", "Encontrar el número con las pistas «más grande» y «más pequeño». La recta enseña dónde puede estar todavía.",
     ["Nivel 1 (desde 3º): del 1 al 20 (3 estrellas con 5 intentos o menos).", "Nivel 2 (desde 3º): del 1 al 100 (con 7 o menos).", "Nivel 3 (desde 4º): del 1 al 1000 (con 10 o menos)."]),
    ("condiciones", "¿Qué hace el programa?", "4º-6º", "Leer un programa con condiciones (bloques de Scratch o de MakeCode), mirar el valor de la variable o del sensor y elegir qué hace. Algunos valores son justo el de la condición: «mayor que 10» no incluye el 10.",
     ["Niveles 1 y 2 (desde 4º): si… entonces (a veces no hace nada) y si… si no.", "Nivel 3 (desde 5º): tres caminos.", "Nivel 4 (5º y 6º): con «y» (dentro de un intervalo) y con «o» (fuera)."]),
    ("poligonos", "La tortuga y los polígonos", "4º-6º", "Completar «repetir [ ] veces: mover 100 pasos y girar [ ] grados» para dibujar la figura que se pide. Si no sale, la pista recuerda la cuenta (360 entre el número de lados) sin dar el resultado.",
     ["Nivel 1 (desde 4º): cuadrado, triángulo, hexágono y pentágono, en ese orden.", "Nivel 2 (5º y 6º): 8, 9, 10 y 12 lados.", "Nivel 3 (6º, o para quien va rápido): estrellas, que dan varias vueltas (5 puntas: 144 grados)."]),
    ("binario", "Cartas binarias", "3º-6º", "Cartas con 1, 2, 4, 8, 16 y 32 puntos: boca arriba cuentan (1) y boca abajo no (0). Así se escriben los números en binario.",
     ["Niveles 1 y 2 (desde 3º): ¿qué número forman? (4 y 5 cartas).", "Nivel 3 (desde 4º): forma el número dando la vuelta a las cartas (hasta 31).", "Nivel 4 (5º y 6º): con 6 cartas (hasta 63)."]),
    ("velocidad", "Velocidad × tiempo", "5º-6º", "El coche Nezha a una velocidad fija: distancia = velocidad × tiempo. Después de responder, el coche recorre la pista.",
     ["Nivel 1 (5º): ¿cuántos centímetros?", "Nivel 2 (5º): con medios segundos.", "Nivel 3 (6º): ¿cuánto tiempo? (dividir).", "Nivel 4 (6º): ¿qué velocidad? (dividir)."]),
    ("cifrado", "Mensajes secretos", "3º-6º", "Descifrar palabras con una clave: números (A = 1, con la Ñ), símbolos y desplazamientos de letras (el cifrado de César). Teclado de letras en la pantalla.",
     ["Niveles 1 y 2 (desde 3º): código de números y de símbolos.", "Nivel 3 (desde 4º): cada letra va 3 puestos después.", "Nivel 4 (desde 4º): descubrir, probando, cuántos puestos se ha movido."]),
    ("pixel", "Píxel art", "3º-4º", "Pintar un dibujo siguiendo el código de cada fila (cuántos cuadrados seguidos de cada color). Se pinta tocando o arrastrando el dedo.",
     ["Para empezar: la flecha (5 × 5).", "Después: el corazón, el pez, la casa y el robot (10 × 10).", "3 estrellas si sale bien a la primera."]),
    ("regla", "La regla secreta", "3º-6º", "La máquina tiene una regla sobre los números del 1 al 30. Se tocan números para ver cuáles la cumplen y, después de probar al menos 3, se elige la regla entre cuatro.",
     ["Nivel 1 (desde 3º): par, impar, mayor que, acaba en…", "Nivel 2 (desde 3º): las tablas del 3, 4, 5, 6, 7 y 9 (debajo pone «múltiplo de», para 5º y 6º).", "Nivel 3 (5º y 6º): con «y», «o» y «no»."]),
    ("balanza", "Ordenar con la balanza", "3º-6º", "Ordenar cajas de más ligera a más pesada comparándolas de dos en dos en la balanza: un algoritmo de ordenación. Con menos pesadas, más estrellas.",
     ["Nivel 1 (desde 3º): 3 cajas (3 estrellas con 3 pesadas o menos).", "Nivel 2 (desde 4º): 4 cajas (con 5 o menos).", "Nivel 3 (5º y 6º): 5 cajas (con 8 o menos). Reto extra: con 7, el mínimo que asegura el orden."]),
]

# Para la diversidad del aula (se ve en la página de cada reto): si cuesta, si va rápido y la ayuda que trae la pantalla.
# Todos tienen además «Escuchar» (lee la pantalla en voz alta) y se juegan sin tiempo, sin sonidos y sin clasificaciones.
SEGUNDA = "El primer fallo de cada reto no cuenta: sale una pista que dice cómo pensarlo, sin dar la respuesta."
ADAPTA = {
    "robot": ("Niveles 1 a 3. Antes de ejecutar, la pareja dice cada bloque en voz alta y lo sigue con el dedo en el tablero.",
              "Los niveles 9 y 10 con 3 estrellas, y explicar a otra pareja qué se repite.",
              "Se puede ejecutar todas las veces que haga falta; si choca, se queda marcado el bloque que falla."),
    "coordenadas": ("Nivel 1, con el dedo: primero se va por la x y después se sube por la y.", "Nivel 5, el escenario de Scratch: ¿dónde está el (0, 0)?", SEGUNDA),
    "variables": ("Nivel 1, con una tabla en papel (paso y cuánto vale) o un vaso con tapones como «caja».", "Nivel 4, y explicar por qué «dar el valor» borra lo que había.",
                  SEGUNDA + " Si se vuelve a fallar, sale la tabla paso a paso."),
    "cubos": ("Nivel 1 con cubos encajables en la mesa: construir la figura y contarla piso a piso, como en la pista.", "Nivel 3, y dibujar en cuadrícula la vista que no se ha preguntado.",
              SEGUNDA + " Al contar, la pista enseña la figura piso a piso."),
    "adivina": ("Nivel 1 con una recta del 1 al 20 en papel, tachando los números que ya no pueden ser.", "Nivel 3 en 10 intentos o menos, y explicar por qué conviene preguntar por la mitad.",
                "La recta enseña en azul dónde puede estar todavía el número, y avisa si se pregunta uno ya descartado."),
    "condiciones": ("Niveles 1 y 2, leyendo el programa en voz alta: «si puntos es mayor que 10, entonces…».", "Nivel 4, y probar con el otro editor (Scratch o MakeCode).",
                    "Después de cada respuesta se explica por qué, también cuando el valor es justo el de la condición."),
    "poligonos": ("Solo el cuadrado y el triángulo. Antes, la clase gira el cuerpo (un cuarto de vuelta son 90 grados); la división 360 : n, con calculadora si hace falta.",
                  "Nivel 3: las estrellas, y descubrir por qué 144 grados dibuja una estrella de 5 puntas.", SEGUNDA + " Las casillas se quedan para corregir solo lo que falla."),
    "binario": ("Nivel 1 con cartas de papel y fichas para contar los puntos.", "Nivel 4, y escribir en binario el día de su cumpleaños.", SEGUNDA),
    "velocidad": ("Nivel 1 con una tabla de 1, 2, 3… segundos, sumando la velocidad cada vez.", "Niveles 3 y 4, e inventar un problema para la pareja.", SEGUNDA),
    "cifrado": ("Nivel 1: las primeras palabras son cortas y, al tocar un número del mensaje, se ilumina en la clave.", "Nivel 4, y cifrar una palabra para que la descifre otra pareja.",
                SEGUNDA + " Si la palabra está casi bien, se subrayan las letras que fallan."),
    "pixel": ("La flecha (5 × 5), tocando cada fila del código para marcarla en el dibujo.", "El robot, y después inventar un dibujo y su código en papel cuadriculado.",
              "Al comprobar se marcan los cuadrados que no están bien, y se puede seguir pintando."),
    "regla": ("Nivel 1, probando los números en orden (1, 2, 3…). En el nivel 2, con la tabla de multiplicar a la vista.", "Nivel 3, descubriendo la regla con los menos números posibles.",
              "Si se elige mal la primera vez, esa opción se tacha y se prueban 2 números más antes de volver a elegir."),
    "balanza": ("Nivel 1 con tres objetos de verdad y las manos como balanza; apuntar «A pesa menos que B».", "Nivel 3 con 7 pesadas o menos (el reto extra).",
                "«Lo que sabemos» apunta cada pesada. Si el orden no está bien, dice qué dos cajas hay que cambiar."),
}
