# Guías para el docente de las herramientas para proyectar (salen en un desplegable bajo cada herramienta).
# Cada guía: idea (qué es, en una o dos frases), contar (guion breve para la clase, en el orden de uso),
# preguntas [(pregunta, [pistas de menos a más], solución en markdown)], mates (vínculo con el área) y saber [(texto, url)].
# Las preguntas hacen pensar: primero la pregunta, después las pistas y solo al final la solución.

GUIAS = {
    "binario": {
        "idea": "Cinco cartas con **1, 2, 4, 8 y 16 puntos**: cada una tiene el doble que la de su derecha. "
                "Cada carta solo puede estar **visible (1)** o **tapada (0)**, y con esas dos posiciones se forma cualquier número del 0 al 31. "
                "Es el **sistema binario**, el que usan los ordenadores: por dentro solo tienen interruptores encendidos o apagados.",
        "contar": [
            "Destapa las cartas una a una, de derecha a izquierda: 1, 2, 4… «¿Cuántos puntos tendrá la siguiente?». Que descubran que **cada carta tiene el doble**.",
            "Tapa todas y pide un número pequeño, por ejemplo el 5. «¿Qué cartas destapo?» → 4 + 1. Fíjate en la línea «En binario»: **00101**.",
            "Explica la regla: **carta visible = 1, carta tapada = 0**. El 5 se escribe 00101, igual que nosotros escribimos 5 con una cifra.",
            "Une la idea con la tecnología: un ordenador o la micro:bit no tienen cartas, tienen **millones de interruptores diminutos** (encendido = 1, apagado = 0). Con ellos guardan números, letras, fotos y música.",
            "Pulsa **Reto: forma un número** y que la clase lo resuelva. Después, **Contar +1** varias veces seguidas y que miren qué carta cambia más.",
        ],
        "preguntas": [
            ("¿Cuál es el número más grande que se puede formar con las 5 cartas?",
             ["¿Qué pasa si destapas todas?", "Suma 16 + 8 + 4 + 2 + 1."],
             "**31** (todas visibles: 11111). Con 3 cartas, 7; con 4, 15. El máximo es siempre **la carta siguiente menos 1** (32 − 1 = 31)."),
            ("¿Cómo se forma el 13? ¿Y el 21?",
             ["Empieza por la carta más grande que **no se pase** del número.", "Para el 13: ¿cabe el 16? No. ¿El 8? Sí, y quedan 5. ¿El 4? Sí, y queda 1…"],
             "**13 = 8 + 4 + 1 → 01101**. **21 = 16 + 4 + 1 → 10101**. El método (coger siempre la carta más grande que quepa) sirve para cualquier número."),
            ("¿Se puede formar un mismo número de dos maneras distintas?",
             ["Prueba con el 6: ¿hay otra forma además de 4 + 2?", "Cada carta solo se puede usar una vez."],
             "**No**: cada número tiene **una sola forma** de escribirse en binario. Por eso los ordenadores nunca se confunden al leerlo."),
            ("Pulsa «Contar +1» muchas veces. ¿Qué carta cambia más? ¿Cada cuánto cambia la del 2?",
             ["Mira solo la carta del 1 mientras cuentas.", "Apunta en la pizarra cuándo se gira la del 2."],
             "La del **1 cambia siempre** (visible, tapada, visible…); la del **2, cada 2**; la del **4, cada 4**… Como un cuentakilómetros, pero en base 2."),
            ("¿Qué tienen en común los números que llevan la carta del 1 visible?",
             ["Escribe los primeros: 1, 3, 5, 7…", "¿Qué pasa si sumas solo cartas de 2, 4, 8 y 16?"],
             "Son los **impares**. Las demás cartas son pares, así que sin la del 1 la suma siempre es par."),
            ("Si añadiéramos una sexta carta a la izquierda, ¿cuántos puntos tendría? ¿Hasta qué número llegaríamos?",
             ["Sigue el patrón: cada carta tiene el doble que la de su derecha.", "Después suma todas."],
             "**32 puntos**. Con 6 cartas se llega al **63** (64 − 1). Cada carta nueva duplica la cantidad de números que se pueden escribir."),
        ],
        "mates": "Potencias de 2 (1, 2, 4, 8, 16…), dobles, descomposición aditiva de un número, pares e impares, y el **valor posicional**: "
                 "en nuestro sistema cada posición vale 10 veces más (unidades, decenas, centenas); en binario, 2 veces más.",
        "saber": [
            ("CS Unplugged · Números binarios: la actividad original de las cartas, con fichas y guía (en español)", "https://csunplugged.org/es/topics/binary-numbers/"),
        ],
    },
    "cuadricula": {
        "idea": "Un robot en un tablero (5 × 5, 6 × 6 o 7 × 7) que se programa con tarjetas: **avanza**, **gira a la derecha**, **gira a la izquierda** y **REPITE** (×2, ×3, ×4). "
                "Hay mapas del tesoro, cazabichos (programas con errores), retos de figuras y un **modo fácil** con flechas de dirección en el que el robot no gira.",
        "contar": [
            "Repaso 4º-6º: algoritmos en un tablero con coordenadas (x, y). En «¿Dónde acaba?» se predice la casilla final y hacia dónde mira el robot antes de ejecutar; en «Cazabichos» se toca la línea que falla y se comprueba.",
            "Antes de poner tarjetas, alguien señala el camino con el dedo sobre el tablero y la clase lo dice en voz alta.",
            "Ponerse en el lugar del robot: **girar no le mueve de casilla**, solo cambia hacia dónde mira. Ayuda que un alumno gire de pie mirando como el robot.",
            "Ejecutar y, si falla, usar **Paso a paso**: la pregunta es «¿en qué tarjeta empieza a fallar?».",
            "Contar las tarjetas y preguntar: «¿se puede hacer con menos?». Ahí entra REPITE.",
        ],
        "preguntas": [
            ("¿Cuál es el programa más corto para cada mapa del tesoro?",
             ["Mira primero hacia dónde mira el robot al empezar (todos empiezan mirando hacia arriba).", "Cuenta las casillas en línea recta antes de pensar en girar."],
             "- **Mapa 1:** avanza ×3 (3 tarjetas).\n- **Mapa 2:** avanza ×3 (3).\n- **Mapa 3:** avanza, avanza, gira a la derecha, avanza, avanza (5).\n"
             "- **Mapa 4:** avanza, gira a la izquierda, avanza ×3, gira a la derecha, avanza ×2 (8).\n- **Mapa 5:** avanza ×4, gira a la derecha, avanza ×4 (9).\n"
             "- **Mapa 6:** avanza, gira a la derecha, avanza ×2, gira a la izquierda, avanza ×3, gira a la izquierda, avanza ×2 (11).\n- **Tablero 7 × 7:** avanza ×5, gira a la derecha, avanza ×6, gira a la izquierda, avanza (14).\n"
             "- **Modo fácil:** ↑ ×4 y → ×4 (8 flechas).\n\nHay otros caminos igual de cortos; cualquiera que llegue sin chocar está bien."),
            ("Cazabichos: ¿qué tarjetas hay que cambiar?",
             ["Pulsa «Paso a paso» y para en cuanto el robot se aleje del tesoro o vaya a chocar.", "El bicho está en esa tarjeta o en la de antes."],
             "- **Cazabichos 1:** la tarjeta 3 tiene que ser **avanza**.\n- **Cazabichos 2:** la tarjeta 3 tiene que ser **gira a la derecha**.\n"
             "- **Cazabichos 3 (2 bichos):** la 3 tiene que ser **gira a la izquierda** y la 6, **gira a la derecha**.\n- **Cazabichos 4 (2 bichos):** la 5 tiene que ser **avanza** y la 7, **gira a la izquierda**."),
            ("La escalera: ¿cómo se programa con REPITE?",
             ["¿Qué trozo se repite en cada escalón?", "Un escalón es: avanza, gira a la derecha, avanza, gira a la izquierda."],
             "**REPITE ×3** (avanza, gira a la derecha, avanza, gira a la izquierda): 5 tarjetas en lugar de 11. Es la misma escalera de 3 escalones que la de «Bucles: largo o corto»."),
            ("El cuadrado de 3 casillas de lado: ¿cuántas veces se repite «avanza 3, gira»?",
             ["Un cuadrado tiene 4 lados iguales.", "Cada lado: avanza, avanza, avanza y gira."],
             "**REPITE ×4** (avanza, avanza, avanza, gira a la derecha): 5 tarjetas en lugar de 16. El robot vuelve a la casilla de salida."),
        ],
        "mates": "Orientación y giros de un cuarto de vuelta (90°), contar casillas, medir recorridos y la multiplicación como suma repetida (4 veces 4 tarjetas = 16).",
        "saber": [("CS Unplugged · Kidbots: programar un «robot» humano (en español)", "https://csunplugged.org/es/topics/kidbots/")],
    },
    "secuencias": {
        "idea": "Viñetas con pictogramas de rutinas de cada día, desordenadas. Hay que ponerlas en orden: es la idea de **algoritmo**, una lista de pasos en orden. "
                "Se eligieron rutinas con un solo orden posible.",
        "contar": [
            "Repaso 4º-6º: ordenar algoritmos de su día a día (pasar el programa a la micro:bit, sumar en columna, calcular la media, resolver un problema). En algunos vale más de un orden: la herramienta lo acepta y explica por qué.",
            "Leer las viñetas en voz alta, tal como salen, y preguntar: «¿tiene sentido así?».",
            "Buscar primero el paso que va **el primero** y el que va **el último**; los del medio salen después.",
            "Ordenar tocándolas y pulsar **Comprobar**.",
            "Cerrar con la idea: un robot no sabe qué paso va antes; si el orden está mal, el resultado sale mal.",
        ],
        "preguntas": [
            ("¿Qué pasaría si cambiamos dos pasos de sitio? Por ejemplo, secarse antes de aclararse.",
             ["Imagínalo con gestos.", "¿Se quedaría el jabón en las manos?"],
             "Saldría mal: el orden importa. En un programa pasa lo mismo: las mismas instrucciones en otro orden dan otro resultado."),
            ("¿Cuál es el orden de cada rutina?",
             ["Busca el primer paso: ¿qué hay que hacer antes que nada?", "Luego pregunta: ¿qué puede ir justo después?"],
             "- **Lavarse las manos:** abro el grifo → me froto con jabón → me aclaro → me seco con la toalla.\n"
             "- **Lavarse los dientes:** cojo el cepillo → pongo la pasta → me cepillo los dientes → me enjuago la boca.\n"
             "- **Ponerse los zapatos:** me pongo los calcetines → me pongo los zapatos → me ato los cordones → salgo a caminar.\n"
             "- **Hacer una tostada:** cojo una rebanada de pan → la meto en la tostadora → unto la tostada → me la como.\n"
             "- **Plantar una semilla:** siembro la semilla → la riego → sale un brote → crece la planta.\n"
             "- **Cruzar la calle:** me paro en el bordillo → espero: el muñeco está en rojo → el muñeco se pone en verde → miro a los dos lados → cruzo por el paso de cebra.\n"
             "- **Lavarse las manos en 6 pasos:** abro el grifo → me pongo jabón → me froto las manos → me aclaro → cierro el grifo → me seco."),
        ],
        "mates": "Ordinales (primero, segundo, último), antes y después, y orden temporal.",
    },
    "patrones": {
        "idea": "Patrones de figuras que se repiten (AB, AAB, ABB, AABB, ABC, ABCD), un patrón **que crece** (la figura 1 tiene 1 cuadrado, la 2 tiene 2…) y patrones **con bicho**, en los que una figura rompe la regla.",
        "contar": [
            "Repaso 4º-6º: figuras que crecen (¿cuántos tendrá la figura 5? ¿y la 10?), series de números (sumar, restar, el doble, Fibonacci) y series con un número que las rompe.",
            "Decir el patrón en voz alta, con ritmo: «rojo, azul, rojo, azul…».",
            "Buscar **la parte que se repite** (el «trozo» del patrón) y rodearla con el dedo.",
            "Predecir lo que va en cada «?» y tocar para comprobar.",
            "Con bicho: decirlo en voz alta hasta que «suene mal».",
        ],
        "preguntas": [
            ("En el patrón AB, ¿qué figura va en el puesto 10? ¿Y en el 15?",
             ["Escribe los primeros puestos: 1 A, 2 B, 3 A, 4 B…", "¿Qué tienen en común los puestos de la B?"],
             "En AB, los puestos **impares** son A y los **pares**, B: el 10 es **B** y el 15 es **A**."),
            ("En el patrón ABC, ¿qué figura va en el puesto 12?",
             ["El trozo que se repite tiene 3 figuras.", "Cuenta de 3 en 3: 3, 6, 9, 12."],
             "El 12 es múltiplo de 3, así que va la **C**, la última del trozo. En general, se mira el resto de dividir entre el tamaño del trozo."),
            ("En el patrón que crece, ¿cuántos cuadrados tiene la figura 10? ¿Y cuántos hay en total en las 5 primeras figuras?",
             ["Cuenta los cuadrados de las figuras 1, 2 y 3.", "Para el total, suma figura a figura."],
             "La figura 10 tiene **10 cuadrados** (cada figura tiene tantos como su número). En las 5 primeras hay **15**: 1 + 2 + 3 + 4 + 5."),
        ],
        "mates": "Series y regularidades, pares e impares, múltiplos, y el primer álgebra: describir una regla («la figura n tiene n cuadrados»).",
    },
    "bucles": {
        "idea": "Compara un programa largo con el mismo programa escrito con **REPITE** y cuenta las tarjetas que se ahorran. Con la barra se cambia el número de repeticiones.",
        "contar": [
            "Repaso 4º-6º: con los bloques de Scratch, cuántas veces se ejecuta cada bloque, cuándo se cierra una figura (repeticiones × giro = 360), un bucle dentro de otro y «repetir hasta que» con su tabla de vueltas.",
            "Leer el programa largo en voz alta. «¿Qué se repite?»",
            "Ver el programa con bucle: el trozo que se repite va **dentro** de REPITE.",
            "Comprobar que los dos hacen **exactamente lo mismo**, y contar las tarjetas de cada uno.",
            "Mover la barra de repeticiones: ¿cuál crece y cuál se queda igual?",
        ],
        "preguntas": [
            ("¿Cuántas tarjetas tiene cada programa?",
             ["Largo: tarjetas del trozo × veces que se repite.", "Corto: las del trozo más la de REPITE."],
             "- **Palmadas** (REPITE 4): largo 4, corto 2.\n- **Baile** (REPITE 3, 3 tarjetas dentro): largo 9, corto 4.\n"
             "- **Cuadrado** (REPITE 4, 3 dentro): largo 12, corto 4.\n- **Escalera** (REPITE 3, 4 dentro): largo 12, corto 5."),
            ("¿Cuándo se ahorran más tarjetas?",
             ["Sube las repeticiones con la barra y mira los dos números.", "¿Qué pasa con el largo? ¿Y con el corto?"],
             "El largo crece con cada repetición y el corto **no cambia**. Cuantas más veces se repite algo, más se ahorra con un bucle."),
            ("¿Cuántas palmadas hay en «REPITE 3: palmada, palmada»?",
             ["¿Cuántas palmadas hay en cada vuelta?", "¿Cuántas vueltas da?"],
             "**6** = 3 × 2."),
        ],
        "mates": "La multiplicación como suma repetida y la comparación de cantidades (¿cuántas menos?).",
    },
    "semaforo": {
        "idea": "El semáforo de peatones (el muñeco rojo y el verde) para trabajar reglas **SI… ENTONCES** y, en el otro modo, **SI… SI NO**.",
        "contar": [
            "Repaso 4º-6º: la clase mueve el valor del sensor o de las variables, predice qué hará el programa y lo comprueba. Se ilumina la rama que se ejecuta. Cinco niveles: si… entonces, si no, tres caminos (si no, si), «y» y «o».",
            "Leer la regla en voz alta.",
            "Pulsar **Luz al azar**: la clase dice qué hace el peatón antes de pulsar **Ver respuesta**.",
            "En modo SI… SI NO: una sola pregunta y dos caminos.",
        ],
        "preguntas": [
            ("¿Qué diferencia hay entre usar dos reglas SI y una SI… SI NO?",
             ["Escribe las dos reglas: «si rojo… », «si verde…».", "¿Hace falta preguntar dos veces?"],
             "Con SI… SI NO basta **una** pregunta: «si el muñeco está en verde, cruzo; si no, espero». El SI NO recoge todos los demás casos."),
            ("Si el muñeco está en verde, ¿cruzamos sin mirar?",
             ["¿Puede pasar un coche aunque esté en verde para nosotros?"],
             "No: primero se mira a los dos lados. La condición del semáforo no basta; la seguridad añade otra comprobación. En programación también se encadenan condiciones."),
        ],
        "mates": "Lógica de sí o no y clasificación de casos.",
    },
    "clasificador": {
        "idea": "Objetos con pictogramas para clasificar **por tipo**, **por color** o **por tamaño**, y una **regla secreta**: la máquina manda cada objeto a «SÍ cumple» o «NO cumple» y la clase tiene que adivinar la regla.",
        "contar": [
            "Repaso 4º-6º: la regla secreta con números del 1 al 30 (par, múltiplos, mayor o menor que) y reglas con «y», «o» y «no»; y un árbol de decisión de dos preguntas que reparte los números en cuatro cajas, como clasifica una máquina.",
            "Clasificar: tocar un objeto y después la caja donde va.",
            "Cambiar de criterio arriba: el mismo objeto puede ir a otra caja según lo que miremos.",
            "Regla secreta: tocar objetos, ver adónde van y proponer la regla antes de **Desvelar la regla**.",
            "Cerrar con la idea: así aprende una máquina, mirando muchos ejemplos ya clasificados.",
        ],
        "preguntas": [
            ("¿Un objeto puede ir en dos cajas a la vez?",
             ["Piensa en la manzana: ¿qué es por tipo? ¿y por color?"],
             "Con **un** criterio, cada objeto va a una sola caja. Al cambiar de criterio puede cambiar de caja: la manzana es «fruta» por tipo y «rojo» por color."),
            ("Regla secreta: ¿qué objetos conviene probar para descubrirla antes?",
             ["Prueba dos objetos que se parezcan en casi todo.", "Si van a cajas distintas, la regla está en lo que los diferencia."],
             "Las reglas posibles son: es de color rojo, es de color verde, es un animal, es una fruta, es un vehículo y es más grande que una persona. "
             "Conviene probar objetos que descarten varias reglas a la vez y contar cuántos hacen falta."),
        ],
        "mates": "Clasificar según un criterio, atributos (color, forma, tamaño) y tablas de doble entrada.",
    },
    "animales": {
        "idea": "El ordenador piensa uno de 8 animales y la clase lo descubre con preguntas de sí o no. Cada respuesta tacha a los animales que no la cumplen.",
        "contar": [
            "Antes de preguntar: «¿qué pregunta tacha más animales?».",
            "Hacer la pregunta y contar cuántos quedan.",
            "Al final, contar cuántas preguntas han hecho falta e intentar mejorarlo con otro animal.",
        ],
        "preguntas": [
            ("¿Cuál es la mejor primera pregunta?",
             ["Cuenta, para cada pregunta, cuántos animales dicen SÍ y cuántos NO.", "La mejor es la que deja menos animales en el peor caso."],
             "**«¿Es más grande que una persona?»**: separa 3 (caballo, avestruz, ballena) de 5. Las demás preguntas separan 2 de 6."),
            ("¿Cuántas preguntas hacen falta como mucho si se eligen bien?",
             ["Si cada pregunta partiera el grupo justo por la mitad: 8 → 4 → 2 → 1.", "¿Alguna de estas preguntas parte el grupo por la mitad?"],
             "Con preguntas que partieran justo por la mitad bastarían **3**. Con estas 5 preguntas ninguna parte 4 y 4, así que hacen falta **como mucho 4** si se eligen bien."),
            ("Inventad una pregunta que parta los 8 animales justo por la mitad.",
             ["Necesitáis 4 animales en el SÍ y 4 en el NO."],
             "Por ejemplo, «¿vive en el agua o puede volar?»: SÍ al pez, la ballena, el pájaro y la mariposa; NO a los otros cuatro."),
        ],
        "mates": "Clasificar con atributos, mitades y dobles (8, 4, 2, 1) y la búsqueda eficiente.",
    },
    "votaciones": {
        "idea": "Encuestas con gráfico de barras en directo y con escala, un **dado** para estudiar frecuencias y el **dado de la clase**, que compara las tiradas con dados de verdad con 1000 tiradas del ordenador. La pregunta se escribe arriba y en **Mis opciones** se ponen las opciones de cada clase.",
        "contar": [
            "Escribir la pregunta (o dejarla en blanco) y votar con +1.",
            "Leer el gráfico: ¿qué barra es la más alta (la **moda**)? ¿Cuántos votos hay en total? ¿Cuántos más tiene la primera que la segunda?",
            "Dado: predecir antes de tirar y comparar 10 tiradas con 100.",
            "Dado de la clase: cada pareja dicta cuántas veces le ha salido cada número (o se escriben los totales de la pizarra) y se pulsa **Añadir**. Después, **Comparar con 1000 tiradas del ordenador**: ¿en cuál se acercan más las barras a la línea «Si salieran igual»?",
        ],
        "preguntas": [
            ("Si tiramos el dado 100 veces, ¿qué número saldrá más?",
             ["¿Tiene algún número más posibilidades que otro?", "Tirad 100 veces dos o tres veces y comparad."],
             "Cualquiera: los seis tienen **la misma probabilidad** (1 de cada 6). Con 100 tiradas cada número sale **unas 17 veces**, pero casi nunca quedan iguales."),
            ("Si en 10 tiradas sale mucho el 6, ¿el dado está trucado?",
             ["Repite las 10 tiradas varias veces.", "¿Pasa lo mismo con 100?"],
             "No necesariamente. Con **pocas tiradas** hay mucha casualidad; con muchas, las barras se parecen más entre sí."),
            ("Con los dados de la clase, un número ha salido bastante más que otro. ¿Nuestros dados están trucados?",
             ["¿Cuántas tiradas habéis hecho? ¿Y el ordenador?", "En las 1000 del ordenador, ¿las barras se separan tanto de la línea?"],
             "Seguramente no. Con unos cientos de tiradas es normal que un número salga bastante más que otro. Con **1000**, cada número sale **unas 167 veces** y las barras quedan mucho más cerca de la línea. Para sospechar de un dado hacen falta muchas tiradas."),
        ],
        "mates": "Estadística: recogida de datos, gráfico de barras, escala, moda, total y diferencias. Probabilidad: suceso seguro, posible e imposible, y frecuencia.",
    },
    "diagrama": {
        "idea": "Diagramas de flujo para recorrer paso a paso: **óvalo** para empezar y terminar, **rectángulo** para hacer algo y **rombo** para una pregunta de sí o no.",
        "contar": [
            "Señalar las tres formas y qué significa cada una.",
            "Recorrer el diagrama con **Siguiente paso**; en cada rombo, la clase vota SÍ o NO.",
            "Probar el otro camino del rombo y ver adónde lleva.",
        ],
        "preguntas": [
            ("¿Por qué el rombo tiene dos salidas y el rectángulo solo una?",
             ["¿Qué hay dentro de cada forma?"],
             "El rombo es una **pregunta**: tiene un camino para el SÍ y otro para el NO. El rectángulo es una acción: después de hacerla se sigue siempre por el mismo sitio."),
            ("En «Par o impar», ¿se pueden decir «PAR» e «IMPAR» en el mismo recorrido?",
             ["Seguid las flechas desde el rombo.", "¿Por cuántos caminos sale del rombo cada vez?"],
             "**No**: cada vez que se llega a un rombo se sigue **un solo camino**, el del SÍ o el del NO. Los dos caminos se juntan otra vez antes de TERMINA."),
            ("En «Cruzar la calle», ¿qué pasa si el muñeco no está en verde?",
             ["Sigue la flecha del NO."],
             "Espero en el bordillo y vuelvo a mirar el semáforo: el diagrama **vuelve atrás** hasta que la respuesta es SÍ. Eso es un bucle."),
            ("En «Adivina el número», del 1 al 100, ¿cuántos intentos hacen falta como mucho si te dicen «más grande» o «más pequeño»?",
             ["Empieza siempre por la mitad de lo que queda (50, luego 25 o 75…).", "Cada intento parte lo que queda por la mitad."],
             "Con la estrategia de la mitad, **7 intentos como mucho**, porque 2 × 2 × 2 × 2 × 2 × 2 × 2 = 128 es más que 100."),
        ],
        "mates": "Lógica, par e impar, y la estrategia de partir por la mitad.",
    },
    "poligonos": {
        "idea": "Una tortuga dibuja un polígono regular con «repetir n: mover, girar». Se cambian el número de lados y la longitud, y aparece el programa que lo dibuja. En **Rosetón**, el polígono se repite 12 veces girando 30°.",
        "contar": [
            "Dibujar un cuadrado: 4 lados y giro de 90°. «¿Cuánto ha girado en total la tortuga?»",
            "Cambiar los lados y mirar el giro que calcula: 360 ÷ lados.",
            "Probar con muchos lados (12 o más) y ver qué forma sale.",
        ],
        "preguntas": [
            ("¿Cuánto gira la tortuga en un triángulo? ¿Y en un hexágono?",
             ["Al terminar, la tortuga ha dado una vuelta completa: 360°.", "Reparte 360 entre el número de lados."],
             "Triángulo: **120°** (360 ÷ 3). Hexágono: **60°** (360 ÷ 6). Ojo: en el triángulo el giro no es 60°; ese es el ángulo de dentro de la figura."),
            ("¿Qué pasa si ponemos muchísimos lados?",
             ["Prueba con 12 y luego con el máximo."],
             "La figura se parece cada vez más a una **circunferencia**: lados muy cortos y giros muy pequeños."),
            ("¿Por qué el rosetón gira 30° entre polígono y polígono?",
             ["¿Cuántas veces se repite el polígono?"],
             "Porque son **12** polígonos y 12 × 30° = **360°**: una vuelta completa."),
        ],
        "mates": "Polígonos regulares, ángulos y giros, la vuelta completa (360°) y la división.",
    },
    "variables": {
        "idea": "Una variable es una **caja con nombre**: el nombre no cambia; lo que guarda, sí. Cuatro modos, con los bloques escritos como en **Scratch** o en **MakeCode** (botón de arriba): **La caja** (dar el valor frente a sumar), **Juego de cálculo** (puntos y vidas en un juego de verdad, con el programa iluminado), **¿Cuánto vale al final?** (programas cortos paso a paso, con su tabla) y **La mascota** (la variable hambre de 6º S2).",
        "contar": [
            "La caja: antes de ejecutar un bloque, la clase dice cuánto valdrá. «Dar el valor» borra lo que había; «sumar» parte de lo que había.",
            "Juego de cálculo: un alumno contesta y la clase mira qué bloque se ilumina. Con vidas = 0 se cumple la condición y el juego acaba.",
            "¿Cuánto vale al final?: primero se escribe la predicción y después se ejecuta paso a paso. Los programas «Sin valor inicial» e «Intercambiar: con bicho» tienen un error para descubrir.",
            "La mascota: los botones hacen lo mismo que la placa. La variable guarda el estado: cuánta hambre tiene.",
        ],
        "preguntas": [
            ("Si puntos vale 3, sumo 1 dos veces y después pongo puntos a 0, ¿cuánto vale?",
             ["Hazlo paso a paso: 3 → … → …", "¿Qué hace «dar a puntos el valor 0»?"],
             "**0**. «Dar el valor» borra lo que había y pone el número nuevo; «sumar» parte de lo que había."),
            ("Empezamos con 3 vidas y chocamos 3 veces. ¿Qué tiene que pasar?",
             ["¿Cuánto vale vidas tras cada choque?"],
             "Vidas llega a **0** y el juego tiene que terminar: «si vidas = 0 entonces decir “Has perdido”». Es una condición que mira el valor de la variable."),
        ],
        "mates": "Suma y resta, valores que cambian y lectura de un registro paso a paso.",
    },
    "coordenadas": {
        "idea": "El escenario de Scratch con sus ejes: **x** de −240 a 240 (izquierda y derecha) e **y** de −180 a 180 (abajo y arriba). El centro es (0, 0). Cuatro modos: **Explorar** (al pasar el dedo se ve la x y la y de cada punto), **Con bloques** (ir a, sumar a x, dar a x el valor, con retos de predecir dónde acaba el gato), **¿Dónde está?** (leer las coordenadas de una estrella o tocar un punto) y **Dibujar con «ir a»** (figuras uniendo puntos, con esquinas que faltan o que están mal).",
        "contar": [
            "Explorar: llevar el dedo hacia la izquierda y ver cómo la x baja y pasa a negativa; igual con la y hacia abajo.",
            "Con bloques: antes de ejecutar, la clase dice dónde acabará el gato. «Sumar» parte de donde estaba; «ir a» no mira dónde estaba.",
            "¿Dónde está?: primero la x (bajando hasta el eje x) y después la y. Se da por bueno a 15 pasos o menos.",
            "Dibujar: calcular las esquinas con el centro en el (0, 0): los mismos números con distinto signo.",
        ],
        "preguntas": [
            ("¿En qué esquina está el punto (240, 180)? ¿Y (−240, −180)?",
             ["La x grande es la derecha; la y grande es arriba."],
             "(240, 180): **arriba a la derecha**. (−240, −180): **abajo a la izquierda**."),
            ("El gato está en (−100, 50). ¿Dónde acaba si mueve x + 10 tres veces?",
             ["Suma 10 tres veces a la x; la y no cambia.", "Cuidado con los negativos: −100 + 10 = −90."],
             "En **(−70, 50)**."),
        ],
        "mates": "Ejes de coordenadas, números negativos, sumar y restar en la recta numérica.",
    },
    "circuito": {
        "idea": "Un circuito con pila y bombilla y un hueco donde se pone un objeto. Si el objeto **conduce** la electricidad, el camino se cierra y la bombilla se enciende.",
        "contar": [
            "Un circuito es un **camino cerrado**: si se abre en algún sitio, no pasa la electricidad.",
            "Elegir un objeto, votar si se encenderá y pulsar **Probar el circuito**.",
            "Rellenar la tabla de la derecha y buscar qué tienen en común los que conducen.",
        ],
        "preguntas": [
            ("¿Qué tienen en común los objetos que encienden la bombilla?",
             ["Mira la tabla: cuchara, moneda, llave, aluminio…"],
             "Casi todos son de **metal**. La mina del lápiz (grafito) también conduce. El papel, la madera, el plástico, la goma y la lana no conducen."),
            ("El plátano y la mano no encienden la bombilla, pero sirven con Makey Makey. ¿Por qué?",
             ["¿Conducen nada o conducen poco?"],
             "**Conducen muy poco**: no lo bastante para una bombilla, pero Makey Makey nota corrientes muy pequeñas. Por eso sirven como teclas."),
        ],
        "mates": "Clasificar, tablas de registro y predecir y comprobar.",
    },
    "leds": {
        "idea": "La pantalla de la micro:bit: **25 luces** en una cuadrícula de 5 × 5. La **x** va de 0 a 4 hacia la derecha y la **y** de 0 a 4 hacia abajo. Se dibuja tocando las luces.",
        "contar": [
            "Contar las luces: 5 filas de 5 = 25.",
            "Pasar el dedo por encima de una luz: aparecen su x y su y.",
            "Dibujar iconos arriba (corazón, sonrisa…) y contarlos con **Contar luces encendidas**.",
        ],
        "preguntas": [
            ("¿Cuáles son las coordenadas de la luz del centro? ¿Y de la esquina de abajo a la derecha?",
             ["Las coordenadas empiezan en 0, no en 1."],
             "Centro: **(2, 2)**. Abajo a la derecha: **(4, 4)**. Arriba a la izquierda es (0, 0)."),
            ("¿Cuántas luces encendidas tiene el corazón? ¿Y la sonrisa?",
             ["Cuenta fila a fila y suma."],
             "Corazón: **16** (2 + 5 + 5 + 3 + 1). Sonrisa: **7**."),
        ],
        "mates": "Coordenadas, cuadrículas, multiplicación (5 × 5) y conteo por filas.",
    },
    "umbral": {
        "idea": "Un sensor mide algo (luz o temperatura) y el programa lo compara con un número límite, el **umbral**, para decidir. Con luz: si el nivel es **menor** que el umbral, es de noche y sale la luna. Con temperatura: si es **mayor** que el umbral, salta el aviso.",
        "contar": [
            "Mover «lo que mide el sensor» y mirar qué hace el programa.",
            "Leer la frase de abajo: «120 no es menor que 50 → no se cumple».",
            "Mover el umbral: el mismo valor medido puede dar otra decisión.",
        ],
        "preguntas": [
            ("Con luz 120 y umbral 50, ¿sale la luna?",
             ["La regla es: si nivel de luz < umbral."],
             "No: 120 no es menor que 50. Sale la luna cuando el nivel baja de 50."),
            ("¿Qué pasa si ponemos el umbral de luz muy alto, por ejemplo 250?",
             ["¿Qué valores de luz son menores que 250?"],
             "Casi cualquier nivel de luz es menor, así que **sale la luna aunque sea de día**. Un umbral mal puesto hace que el programa decida mal: hay que medir y probar."),
            ("¿Cómo elegiríais el umbral para una luz que se enciende al anochecer?",
             ["Medid la luz de la clase con las luces encendidas y con la persiana bajada."],
             "Se mide en las dos situaciones y se elige un número **entre los dos valores**. Es lo que hacen los ingenieros: medir, probar y ajustar."),
        ],
        "mates": "Comparar números (mayor que, menor que), medir y elegir un valor límite.",
    },
    "velocidad": {
        "idea": "Un robot que avanza a una velocidad durante un tiempo. Antes de arrancarlo, la clase predice la distancia: **distancia = velocidad × tiempo**.",
        "contar": [
            "Elegir velocidad y tiempo, y que cada uno apunte su predicción.",
            "Arrancar y comparar con la regla.",
            "Probar otras parejas de valores y apuntarlas en la tabla.",
        ],
        "preguntas": [
            ("A 20 cm/s durante 2 s, ¿cuánto avanza?",
             ["Cada segundo avanza 20 cm."],
             "**40 cm** = 20 × 2."),
            ("¿Qué velocidad y qué tiempo hacen que recorra 100 cm?",
             ["Busca dos números que multiplicados den 100.", "La velocidad va de 5 en 5 y el tiempo, de medio en medio segundo."],
             "Por ejemplo, **20 × 5**, **25 × 4** o **40 × 2,5**."),
            ("Si doblamos la velocidad y mantenemos el tiempo, ¿qué pasa con la distancia?",
             ["Prueba 10 cm/s y 20 cm/s durante 3 s."],
             "Se **dobla** también (30 cm y 60 cm). Ojo: con el robot Nezha real hay que medir, porque el número de velocidad del programa no son centímetros por segundo exactos."),
        ],
        "mates": "Multiplicación y división, proporcionalidad, medidas de longitud y tiempo, y decimales (2,5 s).",
    },
    "sesgo": {
        "idea": "Una máquina aprende qué es una manzana a partir de ejemplos. Si todas las manzanas que ve son de un color, aprende «manzana = fruta de ese color» y se equivoca: eso es un **sesgo**. Con ejemplos variados acierta. No usa cámara.",
        "contar": [
            "Entrenar con pocos ejemplos parecidos (solo manzanas rojas) y leer lo que ha aprendido.",
            "Probar con otras frutas y ver los errores.",
            "Entrenar con manzanas de varios colores y volver a probar.",
            "Idea final: la máquina aprende de los datos; si los datos fallan, la máquina falla.",
        ],
        "preguntas": [
            ("Si solo ha visto manzanas rojas, ¿qué dirá de una manzana verde? ¿Y de una fresa?",
             ["Lee la regla que ha aprendido."],
             "De la manzana verde dirá que **no** es manzana, y de la fresa (roja) que **sí**. Los dos errores vienen de lo mismo: ha aprendido el color, no la fruta."),
            ("¿Cómo se arregla?",
             ["¿Qué ejemplos le faltaban?"],
             "Con **ejemplos variados**: manzanas rojas, verdes y amarillas. Entonces aprende que lo que importa no es el color."),
        ],
        "mates": "Clasificar con datos, contar aciertos y errores, y sacar conclusiones de una muestra.",
    },
    "verdad": {
        "idea": "Tarjetas para votar y comprobar. **1º-2º:** ¿puede pasar de verdad o es inventado? **5º-6º:** ¿es verdad, es un bulo o está hecho con IA? Cada respuesta trae su explicación.",
        "contar": [
            "Leer la tarjeta y votar con la mano antes de tocar la respuesta.",
            "Pedir siempre el porqué: «¿en qué te has fijado?».",
            "Leer la explicación y apuntar las pistas en la pizarra.",
        ],
        "preguntas": [
            ("¿Qué pistas tiene un bulo?",
             ["Mira los titulares y mensajes que eran bulos."],
             "Exageraciones y exclamaciones, cosas imposibles, prometer demasiado, pedir que lo reenvíes («¡Pásalo!») y no decir **quién** lo dice. Se comprueba en una fuente oficial o fiable."),
            ("¿Cómo se puede notar que una imagen está hecha con IA?",
             ["Fíjate en las manos y en las formas."],
             "Errores típicos: **manos con dedos de más o de menos**, formas imposibles o que se derriten, textos sin sentido. No siempre se nota: por eso se comprueba de dónde viene."),
        ],
        "mates": "Contar los votos de la clase y comparar.",
    },
    "contrasenas": {
        "idea": "Un medidor de seguridad de contraseñas y el juego «¿cuál es más segura?». Se escriben solo **contraseñas de ejemplo**, nunca una real.",
        "contar": [
            "Escribir un ejemplo y ver qué condiciones cumple: 12 caracteres o más, mayúsculas y minúsculas, números, símbolos y no ser una muy común.",
            "Jugar a los pares: la clase vota cuál es más segura y lo comprueba con el medidor.",
            "Consejo final: una **frase larga** fácil de recordar es mejor que una palabra corta con símbolos.",
        ],
        "preguntas": [
            ("En cada par, ¿cuál es más segura?",
             ["Comprueba la longitud primero.", "Después mira si mezcla tipos de caracteres."],
             "- **Par 1:** «MiPerroSaltaAlas7!» (larga y con de todo) mejor que «pepe».\n- **Par 2:** «Luna.Verde.2026» mejor que «12345678».\n"
             "- **Par 3:** «ElSolDeMadrid» mejor que «sol»: es más larga y mezcla mayúsculas y minúsculas."),
            ("¿Por qué «12345678» es tan mala aunque tenga 8 caracteres?",
             ["¿Cuánta gente la usará?"],
             "Es de las **más usadas**: es lo primero que se prueba para entrar en una cuenta."),
        ],
        "mates": "Contar caracteres y combinar elementos.",
    },
    "temporizador": {
        "idea": "Cuenta atrás de 45 minutos con la fase de la sesión en grande. **Semanal:** arranque 5, misión 7, práctica 23, compartir 5 y cierre 5. **Quincenal:** tarjeta 3, misión 7, práctica 25, compartir 5 y guardar 5.",
        "contar": [
            "Proyectarlo durante la práctica para que el grupo gestione su tiempo.",
            "**Siguiente fase** salta a la fase siguiente si se ha terminado antes.",
        ],
        "mates": "Lectura del tiempo, minutos y segundos, y restas de tiempo.",
    },
    "cifrado": {
        "idea": "Cifra mensajes cambiando cada letra por un **número** (A = 1, B = 2…) o por un **símbolo**. Debajo aparece la clave. El abecedario incluye la Ñ, así que N = 14, Ñ = 15 y O = 16.",
        "contar": [
            "Escribir un mensaje corto y mirar cómo se cifra.",
            "Marcar **Ocultar el mensaje original** y que otro grupo lo descifre con la clave.",
            "Hablar de privacidad: por eso las aplicaciones cifran los mensajes.",
        ],
        "preguntas": [
            ("Descifrad: 8 · 16 · 12 · 1",
             ["Busca cada número en la clave.", "Recuerda que la Ñ es el 15."],
             "**HOLA**."),
            ("¿Es un código seguro?",
             ["¿Qué letras se repiten más en español?"],
             "No: cada letra se cambia siempre por lo mismo, así que se puede romper contando qué número se repite más (en español, la E y la A son las letras más frecuentes). Los cifrados de verdad usan claves mucho más complejas."),
        ],
        "mates": "Correspondencias letra-número, ordinales y frecuencias.",
    },
    "beebot": {
        "idea": "La abeja robot con su botonera real: avanza, retrocede, gira a la izquierda y a la derecha, pausa, **X** (borrar) y **GO**. Las órdenes se guardan en una **memoria escondida** y se ejecutan todas con GO. Funciona igual que Tale-Bot. Hay tapetes de números, abecedario, granja y cuadrícula.",
        "contar": [
            "Antes de cada programa: **X para borrar la memoria**.",
            "Pulsar las órdenes en voz alta y contarlas con los dedos.",
            "GO y comprobar. **Nuevo reto** propone una casilla de destino.",
        ],
        "preguntas": [
            ("La abeja hace cosas raras que no habíamos programado. ¿Por qué?",
             ["¿Qué había en la memoria antes?"],
             "No se borró la memoria: las órdenes nuevas se **añaden** a las anteriores. Hay que pulsar X antes de cada programa."),
            ("Al girar, ¿cambia de casilla?",
             ["Pulsa solo un giro y GO."],
             "No: **gira sobre sí misma**. Para avanzar después del giro hace falta otra orden de avanzar."),
        ],
        "mates": "Contar, sumar y restar en el camino numérico, orientación y giros.",
        "saber": [("CS Unplugged · Kidbots (en español)", "https://csunplugged.org/es/topics/kidbots/")],
    },
    "flota": {
        "idea": "Hundir la flota con coordenadas: la clase contra el ordenador o **dos equipos, cada uno con su propia flota** en su tablero (si aciertas, vuelves a disparar; gana quien la hunda antes). Con **letra y número** (B3) se dispara a casillas. En el **plano (x, y)** se dispara a **puntos**, los cruces de las líneas, como en unos ejes de coordenadas: de 0 a 7, con el (0, 0) abajo a la izquierda, o el plano completo de −4 a 4, con el (0, 0) en el centro y números negativos.",
        "contar": [
            "Antes de disparar, decir la coordenada completa en voz alta.",
            "Agua, tocado o hundido: tras un tocado, ¿dónde conviene disparar?",
            "En (x, y): primero la x (horizontal) y después la y (vertical). El barco está en el punto, no en el cuadrado.",
            "Con negativos: ¿hacia dónde está el −3 en el eje x? ¿Y en el eje y?",
        ],
        "preguntas": [
            ("¿Cuántas casillas ocupan los barcos?",
             ["Suma los tamaños de todos los barcos."],
             "En 5 × 5: barcos de 3, 2, 1 y 1 = **7 casillas** de 25. En 8 × 8 y en el plano de 0 a 7: 4, 3, 3, 2, 2 y 1 = **15** de 64. En el plano de −4 a 4 hay 9 × 9 = **81 puntos** y los mismos 15 ocupados."),
            ("¿En qué parte del plano está el punto (−2, 3)?",
             ["El primer número es la x: ¿a la derecha o a la izquierda del 0?", "El segundo es la y: ¿arriba o abajo del 0?"],
             "**Arriba a la izquierda**: x negativa (2 a la izquierda del eje y) e y positiva (3 por encima del eje x)."),
            ("Después de un «tocado», ¿dónde disparamos?",
             ["Los barcos están en línea recta."],
             "En las casillas **vecinas** (arriba, abajo, izquierda, derecha). Cuando hay dos tocados seguidos, se sigue en esa misma línea."),
        ],
        "mates": "Coordenadas, cuadrículas, ejes y puntos del plano, números negativos, fracciones del total (7 de 25) y estrategia.",
    },
    "pixelart": {
        "idea": "Dibujos secretos descritos con números fila a fila, como guarda un ordenador una imagen: en cada fila se dice **cuántas casillas seguidas** hay de cada color. En **Pintar y ver el código** se dibuja libre y aparece su código.",
        "contar": [
            "Leer la primera fila del código en voz alta: «3 blancas, 1 negra…».",
            "Pintar fila a fila, de izquierda a derecha.",
            "Pulsar **Comprobar** y, si hace falta, **Ver solución**.",
        ],
        "preguntas": [
            ("¿Cuántos números hacen falta para una fila toda del mismo color?",
             ["Mira cómo se escribe una fila blanca entera."],
             "**Uno**: «10 blancas». Por eso las imágenes con muchas zonas iguales ocupan menos: es una forma de **comprimir**."),
            ("¿Cuántas casillas tiene el dibujo del corazón? ¿Y la flecha?",
             ["Multiplica filas por columnas."],
             "El corazón, la casa, el robot y el pez son de 10 × 10 = **100** casillas; la flecha, de 5 × 5 = **25**."),
        ],
        "mates": "Cuadrículas, multiplicación, conteo y descomposición de un número (10 = 3 + 1 + 6).",
        "saber": [("CS Unplugged · Representación de imágenes (en español)", "https://csunplugged.org/es/topics/image-representation/")],
    },
    "laberinto": {
        "idea": "Seis niveles con bloques tipo Scratch para llevar al robot a la meta: avanzar, girar, «repetir hasta la meta» y bloques «si hay camino». Cada nivel tiene un **máximo de bloques**.",
        "contar": [
            "Leer el consejo del nivel y el máximo de bloques.",
            "Señalar el camino con el dedo antes de programar.",
            "Para meter bloques dentro de un bloque naranja, se toca dentro de él.",
        ],
        "preguntas": [
            ("¿Cuál es una solución de cada nivel?",
             ["Niveles 1 y 2: cuenta las casillas.", "Del 3 en adelante: ¿qué trozo se repite hasta llegar?"],
             "- **Nivel 1:** avanzar, avanzar (2 bloques).\n- **Nivel 2:** avanzar, avanzar, girar derecha, avanzar, avanzar (5).\n"
             "- **Nivel 3:** repetir hasta la meta (avanzar) (2).\n- **Nivel 4:** repetir hasta la meta (avanzar, girar izquierda, avanzar, girar derecha) (5).\n"
             "- **Nivel 5:** repetir hasta la meta (si hay camino a la izquierda → girar izquierda; avanzar) (4).\n"
             "- **Nivel 6:** repetir hasta la meta (si hay camino delante → avanzar; si no → girar derecha) (4).\n\nTodas están comprobadas en la herramienta."),
            ("En el nivel 6, ¿por qué funciona «si hay camino delante, avanza; si no, gira»?",
             ["Sigue el camino con el dedo: ¿qué hace el robot en cada esquina?"],
             "Porque en este laberinto, cada vez que el robot se encuentra una pared, el camino sigue **a su derecha**. El programa no sabe dónde está la meta: va decidiendo en cada casilla."),
        ],
        "mates": "Orientación, conteo y la idea de repetir hasta que se cumple una condición.",
    },
    "simon": {
        "idea": "Secuencias de colores, flechas y sonidos que crecen un paso en cada ronda. Salen alumnos a repetirla. Una secuencia es un programa: **el orden importa**.",
        "contar": [
            "Mirar y escuchar la secuencia entera antes de tocar.",
            "Decirla en voz alta («arriba, derecha, arriba») ayuda a recordarla.",
            "Marcar **Ver la secuencia escrita** para verla como un programa.",
        ],
        "preguntas": [
            ("¿Qué trucos ayudan a recordar secuencias largas?",
             ["¿Es más fácil recordar 6 cosas sueltas o 2 grupos de 3?"],
             "Decirla en voz alta, **agruparla en trozos** de 2 o 3 y buscar si se repite algo. Los programadores también agrupan pasos."),
            ("Con 4 flechas, ¿cuántas secuencias distintas de 3 pasos hay?",
             ["Para el primer paso hay 4 opciones; para el segundo, otras 4…"],
             "**64** = 4 × 4 × 4."),
        ],
        "mates": "Secuencias, memoria de trabajo y, en los cursos altos, combinaciones (4 × 4 × 4).",
    },
    "balanza": {
        "idea": "Cajas con pesos ocultos que hay que ordenar de la más ligera a la más pesada comparándolas **de dos en dos** en una balanza. Es un **algoritmo de ordenación**, como los que usan los ordenadores para ordenar listas.",
        "contar": [
            "Elegir dos cajas y **Comparar en la balanza**; si están mal colocadas, **Cambiar de sitio**.",
            "Apuntar el número de comparaciones: el reto es usar las menos posibles.",
            "Al final, **Comprobar el orden**.",
        ],
        "preguntas": [
            ("¿Cuántas comparaciones hacen falta para encontrar la caja más pesada?",
             ["Compara la ganadora con la siguiente, como en un torneo."],
             "**Una menos que el número de cajas:** 3 con 4 cajas, 5 con 6 y 7 con 8."),
            ("Si comparamos todas las parejas posibles, ¿cuántas comparaciones son? ¿Se puede con menos?",
             ["Con 4 cajas: A con B, C y D; B con C y D…"],
             "Todas las parejas: **6** con 4 cajas, **15** con 6 y **28** con 8. Con un buen método bastan menos: como mucho **5** con 4 cajas, **10** con 6 y **16** con 8. Eso es optimizar un algoritmo."),
        ],
        "mates": "Comparar y ordenar, más pesado y más ligero, y contar parejas.",
        "saber": [("CS Unplugged · Redes de ordenación (en español)", "https://csunplugged.org/es/topics/sorting-networks/")],
    },
    "paridad": {
        "idea": "Un truco de magia: se añaden una fila y una columna de cartas para que **cada fila y cada columna tengan un número par** de cartas azules. Si alguien da la vuelta a una carta, el mago la encuentra. Así detectan los ordenadores los errores al guardar o enviar datos.",
        "contar": [
            "Paso 1: la cuadrícula de 5 × 5 al azar.",
            "Paso 2: el «mago» añade la fila y la columna de paridad.",
            "Paso 3: el mago no mira y un alumno da la vuelta a **una** carta.",
            "Paso 4: el mago busca la fila y la columna con un número **impar** de azules: la carta está en el cruce.",
        ],
        "preguntas": [
            ("¿Por qué funciona el truco?",
             ["Antes del cambio, ¿cómo era el número de azules de cada fila y columna?"],
             "Todas las filas y columnas tenían un número **par** de azules. Al girar una carta, su fila y su columna pasan a **impar**: el cruce señala la carta."),
            ("¿Y si dan la vuelta a dos cartas?",
             ["Prueba con dos cartas de la misma fila."],
             "Puede que el mago **vea que hay un error pero no sepa dónde**: si están en la misma fila, esa fila vuelve a ser par y solo cambian dos columnas. Por eso los ordenadores usan códigos más completos."),
        ],
        "mates": "Pares e impares y razonamiento lógico.",
        "saber": [("CS Unplugged · Detección y corrección de errores (en español)", "https://csunplugged.org/es/topics/error-detection-and-correction/")],
    },
    "quiensale": {
        "idea": "Elige al azar quién sale a la pizarra **sin repetir** hasta que hayan salido todos, y lleva el marcador de hasta 4 equipos. Se puede usar con números de lista o con nombres de equipo.",
        "contar": [
            "Poner el número de alumnos (o pegar la lista de equipos) y pulsar **Usar esta lista**.",
            "**¿Quién sale?** elige a alguien que todavía no ha salido.",
            "El marcador se pone a cero con su botón.",
        ],
        "mates": "Azar, conteo y registro de puntos.",
    },
}
