# La misión de cada sesión contada para la clase (la usa el modo proyección).
# La ficha de la sesión es para el docente; esto es lo que ve el alumnado en la pizarra: qué vamos a hacer hoy,
# en frases cortas, y el reto extra sin la solución.
# Clave: id de la sesión. Dentro, una lista de frases por propuesta: "A", "B", "C"… o "D" (desarrollo, si no hay propuestas),
# y "extra" (el reto para quien termine).
MISION = {
    # ---------------------------------------------------------------- 1º
    "c1-s1": {"A": ["El profe es un robot: solo entiende «avanza», «gira a la derecha» y «gira a la izquierda».", "Le damos órdenes de una en una hasta llevarlo al tesoro.", "¿Cuántas órdenes han hecho falta?"],
              "B": ["El robot de la pizarra mira hacia donde apunta su nariz.", "Por turnos, cada uno pone una tarjeta. Antes de probar: ¿qué va a pasar?", "¡Hasta llegar al tesoro!"],
              "extra": "Escribid todas las tarjetas antes de mover al robot: ¡eso es un programa!"},
    "c1-s2": {"A": ["Las viñetas están desordenadas.", "¿Podemos secarnos antes de lavarnos?", "Las ordenamos entre todos y comprobamos."],
              "B": ["Cada grupo tiene viñetas mezcladas.", "Las ordenamos de izquierda a derecha.", "Las leemos: primero, después, luego, por último."],
              "extra": "Tapad una viñeta: ¿cuál falta?"},
    "c1-s3": {"A": ["¿Cómo se hace una tostada?", "Se lo explicamos a un robot: hay que decir cada paso, y en orden.", "Ordenamos los pasos en la pizarra."],
              "B": ["Tenemos viñetas de tres tareas mezcladas.", "Separamos las tareas y ordenamos los pasos de cada una.", "Cada grupo cuenta su tarea a la clase."],
              "extra": "Inventad un paso que falte."},
    "c1-s4": {"A": ["Programamos entre todos el camino al tesoro, con flechas.", "Después, en parejas: mapas del tesoro en papel.", "Dibujamos una flecha en cada casilla del camino."],
              "B": ["Uno pone las flechas en fila; otro mueve el robot siguiéndolas.", "¿Llega al tesoro sin chocar con las rocas?", "Cambiamos el tesoro de sitio y otra vez."],
              "extra": "Mapas 5 y 6: ¿cuál es el camino más corto?"},
    "c1-s5": {"A": ["Palmada, palmada, pie… ¿qué viene ahora?", "Descubrimos qué va en el «?» de la pizarra.", "Inventamos nuestros patrones."],
              "B": ["Completamos la ficha de patrones.", "Primero decimos el patrón en voz alta.", "Coloreamos lo que viene después."],
              "extra": "El patrón que crece: ¿cuántos cuadrados tendrá la figura siguiente?"},
    "c1-s6": {"A": ["El robot no llega al tesoro: ¡hay un bicho!", "Lo miramos paso a paso: ¿en qué tarjeta empieza a fallar?", "Cambiamos la tarjeta mala y probamos otra vez."],
              "B": ["Este programa tiene un bicho.", "Seguimos las flechas con el dedo.", "Rodeamos la flecha que falla y dibujamos la buena."],
              "extra": "Meted un bicho en un mapa para que lo encuentre otra pareja."},
    "c1-s7": {"A": ["Conocemos a Tale-Bot: sus flechas, el GO y el botón de borrar.", "Antes de cada camino nuevo, ¡borramos!", "Por turnos, programamos caminos de 1 a 3 pasos."],
              "B": ["Programamos la abeja de la pizarra: ¿dónde acabará?", "Pulsamos GO otra vez sin borrar: ¿qué pasa?", "Después, lo probamos con Tale-Bot."],
              "C": ["Una aventura con Tale-Bot: formas y caminos por el tapete."],
              "extra": "Un camino de 4 o 5 pasos con un giro: ¿en qué casilla acabará?"},
    "c1-s8": {"A": ["Primero ponemos en la mesa las tarjetas del camino.", "Después, el piloto pulsa los botones en el mismo orden y GO.", "Si no llega, buscamos la tarjeta que falla."],
              "B": ["Carrera de metas: tres fichas, de la más fácil a la más difícil.", "¿Hasta qué meta llega vuestro grupo?"],
              "extra": "Esquivad dos rocas por el camino más corto."},
    "c1-s9": {"A": ["Dos programas: uno largo y otro corto, con REPITE.", "Los hacemos con palmadas: ¿hacen lo mismo?", "¿Cuál es más corto?", "¡Y ahora, el baile!"],
              "B": ["Cada grupo inventa un baile: 2 tarjetas y REPITE delante.", "Otro grupo lo baila leyendo las tarjetas.", "Nos cambiamos los bailes."],
              "extra": "¿Cuántas palmadas hay en «REPITE 3: palmada, palmada»?"},
    "c1-s10": {"A": ["Un programa es un tren de bloques que empieza con la bandera.", "Se lee de izquierda a derecha.", "Cada grupo monta un programa y otro grupo lo ejecuta.", "Y si quitamos la bandera, ¿empieza?"],
               "B": ["Emparejamos cada flecha con el bloque que hace lo mismo.", "Traducimos un camino de flechas a bloques."],
               "extra": "Un programa de 6 bloques o más."},
    "c1-s11": {"A": ["Conocemos a True True: no tiene botones, lee tarjetas.", "Primero escribimos el camino con bloques de papel.", "Después ponemos las tarjetas del robot en el mismo orden y probamos."],
               "B": ["Tres metas en el tapete: en línea recta, en L y en U.", "¿Hasta qué meta llegáis?"],
               "extra": "El camino en U con el menor número de tarjetas."},
    "c1-s12": {"A": ["La escalera, primero sin REPITE: ¿cuántas tarjetas?", "Ahora con REPITE: ¿cuántas tarjetas?", "Hacemos la escalera con el robot."],
               "B": ["El robot recorre un cuadrado de 2 casillas de lado.", "¿Cuántas veces se repite «avanza, avanza, gira»?"],
               "extra": "Un rectángulo de 2 × 3: ¿qué se repite y cuántas veces?"},
    "c1-s13": {"A": ["El robot sale de casa, va al árbol, da una vuelta y vuelve.", "Programamos la historia paso a paso.", "Cambiamos un bloque: ¿cómo cambia la historia?"],
               "B": ["Cada grupo coloca la casa, el árbol y el cole en su tablero.", "Escribimos el paseo del robot con bloques.", "Otro grupo lo ejecuta."],
               "extra": "Que el robot dé dos vueltas al árbol con un REPITE."},
    "c1-s14": {"A": ["Escribimos con flechas un programa para llegar al tesoro.", "Lo probamos en Tale-Bot, con botones.", "Y después en True True, con tarjetas: ¿llega igual?"],
               "B": ["Dictamos un camino para la abeja de la granja.", "Lo apuntamos con flechas y lo comprobamos.", "Después lo hace el robot del aula."],
               "extra": "Que otro grupo adivine a qué ficha llega vuestro programa."},
    "c1-s15": {"A": ["Inventamos un espectáculo para el robot.", "Lo dibujamos: cómo empieza, qué pasa y cómo termina.", "Lo escribimos con bloques: con movimiento y un REPITE.", "Lo probamos con el robot."],
               "B": ["Escribimos el espectáculo con bloques de papel.", "Lo probamos con el robot de la pizarra."],
               "C": ["Bailamos al ritmo con True True."],
               "extra": "Un espectáculo con dos REPITE distintos."},
    "c1-s16": {"A": ["Cada grupo enseña su espectáculo.", "Decimos una cosa que nos ha gustado.", "Al final, cazabichos en la pizarra."],
               "B": ["Ejecutamos el programa de otro grupo.", "¿Sale lo que querían? Si no, ¡hay un bicho!"],
               "extra": "Meted un bicho a propósito para que otro grupo lo encuentre."},
    "c1-s17": {"D": ["Elegimos una misión para el robot: por ejemplo, llevar la carta a correos.", "Dibujamos la salida, una parada y la meta.", "Repartimos los roles."],
               "extra": "Añadid una segunda parada."},
    "c1-s18": {"A": ["Colocamos en el tapete el escenario de nuestra misión.", "Probamos una primera ruta hasta la parada."],
               "B": ["Una ciudad con semáforo: el robot tiene que parar en el semáforo."],
               "extra": "Poned una roca en el camino: ¿cómo la rodea el robot?"},
    "c1-s19": {"D": ["Escribimos la ruta con bloques y la repasamos con el dedo.", "Ponemos las tarjetas del robot en el mismo orden y probamos.", "Si falla, buscamos la tarjeta que falla, sin empezar de cero."],
               "extra": "La misión de vuelta: de la meta a la salida."},
    "c1-s20": {"A": ["Un programa largo y otro con REPITE: ¿cuántas tarjetas nos ahorramos?", "¿Podemos hacer nuestra misión con menos tarjetas?", "Antes… tarjetas. Ahora… tarjetas."],
               "B": ["Somos detectives: miramos el programa de otro grupo.", "¿Sobra alguna tarjeta? ¿Se puede juntar con REPITE?"],
               "extra": "¿Cuál es el programa más corto de la clase? ¿Llega igual?"},
    "c1-s21": {"D": ["Probamos la misión de otro grupo.", "Rellenamos la ficha de caritas.", "Volvemos y arreglamos la nuestra."],
               "extra": "Proponed una mejora al otro grupo."},
    "c1-s22": {"D": ["Ensayamos: «Nuestra misión es… El robot sale de… Usamos… tarjetas».", "El portavoz lo cuenta y los demás mueven el robot."],
               "extra": "Contad el camino con palabras de posición: delante, detrás, a la derecha…"},
    "c1-s23": {"D": ["Cada grupo presenta su misión: qué hace el robot y cómo lo programamos.", "Contamos un bicho que encontramos.", "¡El robot hace la misión en directo!"],
               "extra": "Adivinad cuántas tarjetas usó cada grupo antes de que lo diga."},
    "c1-s24": {"A": ["Repetimos nuestras misiones favoritas.", "¡Recogemos el pasaporte completo!"],
               "B": ["Enseñamos a los de Infantil a mover el robot."],
               "extra": "Inventad un reto para el curso que viene."},
    # ---------------------------------------------------------------- 2º
    "c2-s1": {"A": ["El robot vuelve: ¿qué órdenes entiende?", "Regla nueva: primero escribimos todo el programa y después lo probamos.", "Revisamos entre todos antes de pulsar «Ejecutar»."],
              "B": ["Cada grupo coloca el robot, el tesoro y tres rocas en su tablero.", "Escribimos el camino con flechas en fila.", "Otro grupo lo comprueba moviendo el robot."],
              "extra": "El camino con menos tarjetas."},
    "c2-s2": {"A": ["Un algoritmo es una lista de pasos en orden.", "Ordenamos los 6 pasos para lavarse las manos.", "¿Por qué este paso no puede ir antes?", "¿Y si falta un paso?"],
              "B": ["Cada grupo tiene dos rutinas mezcladas.", "Las ordenamos.", "Añadimos un paso que falte."],
              "extra": "Escribid el algoritmo de «preparar la mochila»."},
    "c2-s3": {"A": ["¿Qué va en cada «?»?", "Ahora un patrón que crece: figura 1, figura 2, figura 3…", "¿Cómo será la figura 4? ¿Y la 10?"],
              "B": ["Completamos la ficha de patrones, también el patrón que crece."],
              "extra": "La hoja 2: ¿dónde está el bicho del patrón?"},
    "c2-s4": {"A": ["Dos programas para la escalera: uno largo y otro con REPITE. ¿Hacen lo mismo?", "Ahora el cuadrado con REPITE: el robot deja su rastro."],
              "B": ["Cada grupo escribe un cuadrado con flechas y la tarjeta REPITE.", "Otro grupo lo comprueba en su tablero."],
              "extra": "Un rectángulo de 2 × 3 con REPITE: ¿qué cambia respecto al cuadrado?"},
    "c2-s5": {"A": ["Este programa tiene dos bichos.", "Lo miramos paso a paso y paramos cuando el robot se equivoque.", "Cambiamos la tarjeta mala… y buscamos el segundo bicho."],
              "B": ["En parejas: seguimos el programa con el dedo.", "Rodeamos los dos bichos y escribimos la flecha buena."],
              "extra": "Meted dos bichos en un mapa para otra pareja."},
    "c2-s6": {"A": ["Volvemos a True True: ¿qué entra y qué sale?", "Tres retos: en línea recta, en L y en U.", "¿Cuántas tarjetas ha usado cada grupo?"],
              "B": ["Recicla con True True: el robot lleva cada residuo a su contenedor."],
              "extra": "El camino en U con el menor número de tarjetas."},
    "c2-s7": {"A": ["El robot recorre un cuadrado de 2 casillas de lado.", "Primero sin repetir; después, ¿lo podemos acortar?", "Reto: un rectángulo de 2 × 3."],
              "B": ["Exploramos figuras geométricas con True True."],
              "extra": "El rectángulo de 2 × 3 con REPITE."},
    "c2-s8": {"A": ["¡Misión final! Cuatro pruebas: patrón, camino, bucle y bicho.", "Cada prueba da un número.", "Con los cuatro números, el código secreto."],
              "B": ["Cuatro retos en la pizarra, por equipos: un patrón, un mapa, un bucle y un bicho."],
              "extra": "Inventad una quinta prueba para otro grupo."},
    "c2-s9": {"A": ["SI el muñeco está en rojo, ENTONCES espero en el bordillo.", "SI está en verde, ENTONCES miro a los dos lados y cruzo.", "Cambia la luz: ¿qué regla toca?"],
              "B": ["Cada grupo empareja cada tarjeta SI con su ENTONCES.", "Después inventamos una regla para la clase."],
              "extra": "Probad el modo SI… SI NO."},
    "c2-s10": {"A": ["CUANDO aplaudo → brazos arriba.", "CUANDO suena la campanilla → nos agachamos.", "¡Atentos! Solo reaccionamos a la señal de cada programa."],
               "B": ["Cada grupo monta un programa: CUANDO… y dos acciones.", "Lo lee en voz alta y la clase lo hace cuando oye la señal."],
               "extra": "Un programa con dos señales y una acción que se repite."},
    "c2-s11": {"A": ["El robot cruza la calle por el paso de cebra.", "SI el muñeco está en verde, ENTONCES cruza; SI NO, se para antes.", "Programamos el recorrido según el color que nos toque."],
               "B": ["Con el semáforo de la pizarra: ¿qué hace el robot con cada luz?", "Lo explicamos con la regla."],
               "extra": "Que el robot, después de cruzar, gire y llegue a una meta."},
    "c2-s12": {"A": ["El ordenador ha pensado un animal.", "Lo descubrimos con preguntas de sí o no.", "¿Con cuántas preguntas lo encontramos? ¿Y con menos?"],
               "B": ["Con el árbol de preguntas, cada grupo descubre su animal.", "Cada respuesta nos lleva por un camino del árbol."],
               "extra": "¿Cuál es la mejor primera pregunta?"},
    "c2-s13": {"A": ["Clasificamos por color: SI es rojo, a esta caja; SI NO, a la otra.", "Ahora la máquina tiene una regla secreta.", "Mirad adónde manda cada objeto. ¿Cuál es la regla?"],
               "B": ["Un compañero es la máquina y tiene una regla secreta.", "Le damos objetos y los pone en la caja 1 o en la 2.", "¿Quién adivina la regla completa?"],
               "extra": "Reglas con dos condiciones: «SI es rojo Y es grande…»."},
    "c2-s14": {"D": ["Diseñamos nuestro juego de mesa.", "Elegimos un tema y un título.", "Escribimos al menos 3 reglas: SI caes en…, ENTONCES…"],
               "extra": "Una casilla con SI… SI NO: «SI sacas par, avanza 2; SI NO, retrocede 1»."},
    "c2-s15": {"D": ["Terminamos el tablero.", "Jugamos en parejas al juego del compañero.", "¿Alguna regla tiene un bicho? Lo apuntamos y lo arreglamos."],
               "extra": "Que el compañero proponga una regla nueva. ¿Tiene bichos?"},
    "c2-s16": {"A": ["¡Feria de juegos! Media clase explica su juego y la otra mitad juega.", "Después nos cambiamos.", "Al final, votamos."],
               "B": ["En parejas: jugamos al juego del otro.", "Dos cosas que nos gustan y una idea para mejorar."],
               "extra": "Leed el gráfico de la votación: ¿cuántos votos más tiene el ganador?"},
    "c2-s17": {"D": ["Hoy planificamos nuestro proyecto con el robot.", "Elegimos la salida, la parada y la meta.", "Repartimos los roles."],
               "extra": "Añadid una segunda parada o un obstáculo."},
    "c2-s18": {"D": ["Colocamos el escenario en el tapete.", "Escribimos la ruta con bloques y la pasamos a tarjetas del robot.", "Si falla, la arreglamos sin empezar de cero."],
               "extra": "La ruta de vuelta con el menor número de tarjetas."},
    "c2-s19": {"D": ["Optimizar es conseguir lo mismo con menos tarjetas.", "Contamos nuestras tarjetas: ¿cuántas tenemos antes?", "¿Dónde podemos usar REPITE? ¿Qué sobra?", "¿Cuántas tenemos después?"],
               "extra": "¿Qué grupo ha ahorrado más tarjetas?"},
    "c2-s20": {"D": ["Probamos el proyecto de otro grupo y rellenamos la ficha de caritas.", "Volvemos y arreglamos el nuestro.", "Ensayamos: «Nuestro proyecto es… Lo hemos programado así… Un bicho fue…»."],
               "extra": "Proponed una mejora al otro grupo."},
    "c2-s21": {"D": ["Cada grupo presenta su proyecto y lo enseña con el robot.", "La clase hace una pregunta o dice algo que le ha gustado."],
               "extra": "Antes de cada demostración: ¿cuántas casillas avanzará el robot?"},
    "c2-s22": {"D": ["¡Hola, ScratchJr! Sus bloques son como los de papel.", "Bandera verde y avanzar: ¿qué hace el gato?", "Cambiamos los números.", "Reto: que el gato llegue al otro lado de la pantalla."],
               "extra": "Que el gato cruce con menos bloques."},
    "c2-s23": {"A": ["Dos personajes: cuando tocamos cada uno, hace algo distinto.", "Al menos uno usa repetir."],
               "B": ["Hacemos un zoo: cada animal, al tocarlo, se mueve y dice algo."],
               "extra": "Un tercer personaje que haga un sonido."},
    "c2-s24": {"D": ["Nuestra primera animación: bandera verde, un movimiento, un repetir y un personaje que reacciona al tocarlo.", "Después, visitamos las animaciones de los demás."],
               "extra": "Dos personajes que se mueven a la vez."},
    # ---------------------------------------------------------------- 3º
    "c3-s1": {"A": ["Tres retos para empezar el curso.", "Un mapa: escribimos el programa antes de probarlo.", "Un patrón con bicho: ¿qué figura rompe el patrón?", "Un cazabichos: ¿dónde están los dos bichos?"],
              "B": ["En parejas: una ficha de cazabichos y una de patrones."],
              "extra": "Inventad un mapa con dos rocas para otra pareja."},
    "c3-s2": {"A": ["Un diagrama de flujo es el dibujo de un algoritmo.", "Óvalo: empezar y terminar. Rectángulo: hacer algo. Rombo: una pregunta.", "Lo recorremos paso a paso: en el rombo, ¿SÍ o NO?"],
              "B": ["Completamos el diagrama de «regar una planta».", "Escribimos lo que falta en las cajas vacías.", "Lo comprobamos recorriéndolo en la pizarra."],
              "extra": "Construid el diagrama de «preparar la mochila»."},
    "c3-s3": {"A": ["Un cuadrado con REPITE: avanza, avanza, avanza, gira… ¿cuántas veces?", "Ahora otros polígonos: ¿cuánto hay que girar?", "¿Y para un triángulo?"],
              "B": ["En parejas: uno dicta un programa con REPITE y el otro lo dibuja en la cuadrícula.", "Una escalera, un cuadrado, una almena…"],
              "extra": "El pentágono: ¿cuánto hay que girar?"},
    "c3-s4": {"A": ["Operaciones y polígonos con True True: el robot recorre figuras y resuelve operaciones."],
              "B": ["El robot pasa por casa, el cole y correos hasta la meta.", "Cada grupo programa el recorrido con el menor número de tarjetas.", "¿Cuántas tarjetas ha usado cada grupo?"],
              "extra": "El recorrido con paradas y la vuelta a casa."},
    "c3-s5": {"A": ["La oca de las condiciones.", "«SI sacas par, avanza 2. SI NO, quédate».", "Leemos cada regla en voz alta antes de mover."],
              "B": ["El semáforo: SI está en verde… SI NO…", "Par o impar: decimos un número y recorremos el diagrama."],
              "extra": "Inventad una casilla nueva para la oca con SI… SI NO."},
    "c3-s6": {"A": ["El método del cazabichos: paso a paso y parar en el primer error.", "En parejas: la ficha con tres bichos."],
              "B": ["Cada pareja resuelve un mapa y le mete dos bichos.", "Se lo pasa a otra pareja: ¿los encuentra?"],
              "extra": "Meted tres bichos en vuestro mapa para otra pareja."},
    "c3-s7": {"A": ["Hacemos una encuesta y votamos.", "Copiamos la tabla y dibujamos el gráfico de barras.", "¿Qué es lo más votado? ¿Cuántos votos hay en total?"],
              "B": ["Si tiramos un dado muchas veces, ¿sale más algún número?", "Apuntamos nuestra predicción.", "Tiramos 20 veces, juntamos los datos de la clase y comparamos."],
              "C": ["Usamos una encuesta para decidir algo de verdad en la clase."],
              "extra": "Haced dos preguntas y comparad los dos gráficos."},
    "c3-s8": {"A": ["¡Misión final! Cuatro pruebas: diagrama, bucle, condición y bicho.", "Cada prueba da un número del código secreto."],
              "B": ["Cuatro retos en la pizarra, por equipos: diagrama, bucle, condición y bicho."],
              "extra": "Inventad una quinta prueba para otro grupo."},
    "c3-s9": {"D": ["Conocemos Scratch: escenario, objetos, bloques y zona de programar.", "Primer programa: al hacer clic en la bandera, el gato dice ¡Hola!", "Cambiamos el texto.", "Guardamos con el nombre de la pareja."],
              "extra": "Que el gato diga dos frases seguidas y cambie de disfraz."},
    "c3-s10": {"D": ["Movemos al gato con la bandera y con las flechas del teclado.", "Cada tecla es un evento: empieza su propio programa.", "Reto: que el gato se mueva también arriba y abajo."],
               "extra": "Que el gato empiece siempre en el centro."},
    "c3-s11": {"A": ["El gato baila: repetir 10 veces cambiar de disfraz.", "Añadimos mover dentro del repetir: ¡camina!", "Reto: que baile girando y maullando."],
               "B": ["Dibujamos figuras con el lápiz de Scratch.", "Un cuadrado: repetir 4 veces mover y girar 90.", "Reto: un triángulo o un hexágono. ¿Cuánto hay que girar?"],
               "extra": "El hexágono, o una escalera con el lápiz."},
    "c3-s12": {"D": ["Hoy, una animación con dos personajes que hablan.", "Para que no hablen a la vez: esperar.", "Un diálogo de 4 frases, con fondo y un sonido."],
               "extra": "Un tercer personaje o un cambio de fondo en mitad del diálogo."},
    "c3-s13": {"D": ["Una variable es una caja con nombre que guarda un número.", "Creamos la variable «puntos».", "Cada clic en el gato, un punto.", "¿Qué pasa al pulsar la bandera?"],
               "extra": "Que el gato cambie de sitio al hacer clic: ¡ya es un juego!"},
    "c3-s14": {"D": ["El juego de atrapar: movemos al personaje con las flechas.", "SI toca la manzana, ENTONCES suma un punto.", "La manzana aparece en otro sitio."],
               "extra": "Que la manzana se mueva sola."},
    "c3-s15": {"D": ["Hoy empieza nuestro proyecto en Scratch.", "Primero el plan: lo dibujamos en la hoja de diseño.", "Después, los bloques.", "¡No olvidéis guardar!"],
               "extra": "Un segundo nivel o un contador de fallos."},
    "c3-s16": {"D": ["Terminamos el proyecto.", "Probamos el de otra pareja y rellenamos la ficha.", "Arreglamos el nuestro y guardamos."],
               "extra": "Proponed una mejora concreta a la otra pareja."},
    "c3-s17": {"A": ["¿Qué materiales dejan pasar la electricidad?", "Elegimos un objeto y votamos: ¿se encenderá la bombilla?", "Después lo comprobamos con el kit."],
               "B": ["Probamos objetos en el circuito de la pizarra y apuntamos los resultados."],
               "extra": "Clasificad los conductores en «muy buenos» y «regulares»."},
    "c3-s18": {"D": ["El Makey Makey convierte cualquier objeto que conduce en una tecla.", "Al tocar el aluminio… ¡el gato maúlla!", "Reto: un piano de 4 notas."],
               "extra": "Tocad una melodía conocida con las 4 notas."},
    "c3-s19": {"D": ["Planificamos la pieza de nuestro museo interactivo.", "¿Qué se toca? ¿Qué pasa al tocarlo?", "Al menos 3 botones y un contador.", "Repartimos las tareas."],
               "extra": "Un final: al llegar a 10 toques, la pieza dice algo."},
    "c3-s20": {"D": ["Construimos el mando: plantilla, cartón y aluminio.", "Los botones no pueden tocarse entre sí.", "Al final, primera prueba de conexión."],
               "extra": "Un botón extra con otra forma geométrica."},
    "c3-s21": {"D": ["Cada botón, un evento: ¿qué pasa al pulsarlo?", "Añadimos un contador.", "Otro grupo prueba la pieza y apuntamos los bichos."],
               "extra": "Que el contador reste cuando se falla."},
    "c3-s22": {"D": ["Optimizar: el mismo programa, más corto y más claro.", "¿Cuántos bloques tenemos antes? ¿Y después?", "Otro grupo prueba la pieza y busca bichos."],
               "extra": "¿Quién consigue el programa con menos bloques?"},
    "c3-s23": {"D": ["Cada grupo presenta su pieza: qué es y cómo funciona.", "Contamos un bicho que encontramos y cómo lo arreglamos."],
               "extra": "Explicad con números: cuántos bloques antes y después de optimizar."},
    "c3-s24": {"A": ["¡El museo abre sus puertas!", "Media clase presenta su pieza y la otra la visita.", "Después nos cambiamos."],
               "B": ["Recibimos a los de 2º y les enseñamos nuestra pieza."],
               "extra": "Contad las visitas de cada pieza y haced un gráfico."},
    # ---------------------------------------------------------------- 4º
    "c4-s1": {"A": ["Este juego tiene tres bichos.", "Lo abrimos, jugamos y apuntamos qué falla.", "Encontramos los bichos y los arreglamos."],
              "B": ["Tres retos relámpago en Scratch:", "1. El gato dice hola con la bandera.", "2. Se mueve con las flechas.", "3. Cuenta puntos al hacer clic en él."],
              "extra": "Añadid al juego una mejora vuestra."},
    "c4-s2": {"D": ["¿Cuánto gira la tortuga en cada polígono? Completamos la tabla.", "Dibujamos polígonos con el lápiz de Scratch.", "Un rosetón: un cuadrado repetido 12 veces, girando 30 grados.", "Un repetir dentro de otro: ¡multiplica!"],
              "extra": "Un rosetón de hexágonos: ¿cuántas veces repetir y cuánto girar?"},
    "c4-s3": {"A": ["Recorremos diagramas de decisión: par o impar.", "Adivina el número: el NO vuelve atrás. ¡Es un bucle!"],
              "B": ["Construimos con las formas el diagrama de «adivina el número».", "Otro grupo lo juega siguiéndolo."],
              "extra": "Un diagrama nuevo: «¿es múltiplo de 5?»."},
    "c4-s4": {"D": ["Las variables guardan datos que cambian: puntos y vidas.", "Las creamos en Scratch y les damos un valor al empezar.", "Clic en el personaje: +1 punto. Tecla espacio: −1 vida.", "¿Qué pasa si no las ponemos a 0 al empezar?"],
              "extra": "Una variable «tiempo» que baje de 1 en 1."},
    "c4-s5": {"D": ["El ordenador piensa un número del 1 al 20.", "Le preguntamos y nos dice si hemos acertado.", "Mejora: que diga «es más grande» o «es más pequeño».", "Mejora final: que pregunte hasta que acertemos."],
              "extra": "Que cuente cuántos intentos hemos necesitado."},
    "c4-s6": {"D": ["Programamos el juego de las tablas.", "El ordenador elige dos números al azar y pregunta cuánto es.", "Si acertamos, +1 punto.", "Al final de las 10 preguntas, dice los puntos."],
              "extra": "Tablas hasta el 12, o que cuente también los fallos."},
    "c4-s7": {"A": ["Jugamos al juego de las tablas de otra pareja.", "Rellenamos la ficha de prueba.", "Volvemos y arreglamos el nuestro."],
               "B": ["¡Torneo de bichos! Tres archivos, cada uno con un error.", "Gana la pareja que los arregla antes."],
               "extra": "Fabricad un bicho para otra pareja."},
    "c4-s8": {"D": ["Terminamos y guardamos el juego de las tablas.", "Media clase juega a los juegos de la otra mitad, y después al revés.", "Votamos y leemos el gráfico."],
              "extra": "¿Cuántos votos de diferencia hay entre el primero y el segundo?"},
    "c4-s9": {"D": ["¿Qué tiene todo juego? Personaje, objetivo, obstáculo, puntos y final.", "Diseñamos nuestro videojuego en papel y dibujamos la pantalla.", "Se lo contamos a otra pareja y nos damos una idea."],
              "extra": "Añadid un segundo nivel al diseño."},
    "c4-s10": {"D": ["Elegimos fondo y personaje.", "Lo movemos con las cuatro flechas.", "Que empiece en el centro y no se salga de la pantalla."],
               "extra": "Que el personaje cambie de disfraz al moverse."},
    "c4-s11": {"D": ["Un premio para atrapar: SI lo toca el personaje, suena y cambia de sitio.", "Un enemigo que se mueve solo.", "SI el enemigo nos toca: ¡ay!"],
               "extra": "Dos enemigos con velocidades distintas."},
    "c4-s12": {"D": ["Puntos y vidas: empiezan en 0 y en 3.", "El premio suma un punto; el enemigo quita una vida.", "Con 0 vidas, «Has perdido». Con 10 puntos, «¡Has ganado!»."],
               "extra": "Un premio de otro color que valga más puntos."},
    "c4-s13": {"D": ["Al llegar a 5 puntos, el juego envía un mensaje: nivel 2.", "Al recibirlo, cambia el fondo…", "… y el enemigo va más rápido."],
               "extra": "Un tercer nivel con otro fondo y otra velocidad."},
    "c4-s14": {"D": ["Probamos dos juegos de otras parejas y rellenamos la ficha.", "Leemos lo que nos han escrito.", "Elegimos un bicho y una mejora, y los arreglamos."],
               "extra": "Probad un tercer juego."},
    "c4-s15": {"D": ["Primero arreglamos el bicho, después la mejora.", "Si no encontramos el bicho: ¿qué quería que pasara? ¿Qué pasa? ¿En qué bloque empieza a fallar?", "Otra pareja comprueba el arreglo.", "Y tres normas para navegar seguros."],
               "extra": "Una pantalla de instrucciones o un nivel más."},
    "c4-s16": {"D": ["¡Feria de videojuegos!", "Media clase presenta y la otra juega; después nos cambiamos.", "Al final, votación."],
               "extra": "Una pantalla de instrucciones para vuestro juego."},
    "c4-s17": {"D": ["Recordamos: un circuito es un camino cerrado.", "Con Makey Makey, cada objeto que conduce es una tecla.", "Reto: mover nuestro personaje con 4 bolas de plastilina."],
               "extra": "Cuatro teclas con cuatro sonidos y un personaje que se mueve."},
    "c4-s18": {"D": ["Nuestro encargo: un juego para enseñar algo a los de 2º.", "¿Qué enseña? ¿Cómo se juega? ¿Qué botones tiene?", "Al menos 4 botones, una variable y un si… si no.", "Repartimos las tareas."],
               "extra": "Un modo difícil además del fácil."},
    "c4-s19": {"D": ["Construimos el mando con cartón y aluminio.", "Los botones no pueden tocarse entre sí.", "Mientras, los programadores empiezan en Scratch.", "Al final, prueba de conexión."],
               "extra": "Un botón extra con forma de figura geométrica."},
    "c4-s20": {"D": ["Cada botón, un evento.", "SI la respuesta es correcta, +1 punto; SI NO, «Inténtalo otra vez».", "Probamos cada botón por separado y después el juego entero."],
               "extra": "Que el juego cuente el tiempo que tarda el jugador."},
    "c4-s21": {"D": ["Optimizar: el mismo juego, con un programa más corto y más claro.", "Lo repetido, en un repetir o en un bloque propio.", "Nombres claros y bloques ordenados.", "¿Cuántos bloques antes? ¿Y después?"],
               "extra": "Un bloque propio con un número, por ejemplo «saltar (altura)»."},
    "c4-s22": {"D": ["Probamos el juego de otro grupo como si fuéramos de 2º.", "Apuntamos qué cuesta entender.", "Volvemos y lo mejoramos."],
               "extra": "Una segunda ronda de pruebas después de los arreglos."},
    "c4-s23": {"D": ["Cada grupo presenta su juego: qué enseña, cómo funciona, un bicho que arregló y qué optimizó.", "Y hablamos de huella digital: ¿por qué no hacemos fotos de caras?"],
               "extra": "Explicad con números: cuántos bloques antes y después de optimizar."},
    "c4-s24": {"A": ["Jugamos a los juegos de los demás grupos."],
               "B": ["Recibimos a los de 2º y juegan a nuestro juego."],
               "extra": "Haced el gráfico de votos y leedlo en voz alta."},
    # ---------------------------------------------------------------- 5º
    "c5-s1": {"A": ["Reto relámpago en Scratch, en tres niveles:", "Bucle: un personaje que da vueltas sin parar y cambia de disfraz.", "Variable: que cuente puntos cada vez que hacemos clic en él.", "Condición: si llega a 10 puntos, dice «¡Has ganado!»."],
              "B": ["Este juego tiene tres bichos.", "Lo probamos, encontramos los bichos y los arreglamos."],
              "extra": "El nivel 3 con un si… si no."},
    "c5-s2": {"D": ["La micro:bit es un ordenador diminuto: 25 luces, 2 botones y sensores.", "Primero en el simulador: un corazón al iniciar.", "Botón A, un 1; botón B, un 2.", "Retos: un corazón que late y un contador.", "Al final, ¡a la placa de verdad!"],
              "extra": "Que el contador baje con el botón B y no pase de 0."},
    "c5-s3": {"A": ["Un dado electrónico: al agitar la placa, sale un número del 1 al 6.", "Mejora: una pequeña animación antes del número.", "Investigamos: ¿sale todo más o menos igual?"],
              "B": ["Un contador de pasos: cada sacudida suma un paso.", "Nos la ponemos en el tobillo y caminamos 20 pasos: ¿cuenta bien?"],
              "extra": "Un dado que no repita el número anterior."},
    "c5-s4": {"A": ["Una lamparita de noche: si hay poca luz, se encienden las luces.", "Probamos en el simulador y después tapando la placa.", "Ajustamos el número límite hasta que funcione: el umbral."],
              "B": ["Un termómetro: al pulsar A, enseña la temperatura.", "Medimos en el aula, en la ventana y en el pasillo.", "Hacemos un gráfico con los datos."],
              "extra": "Una barra de luces que crece con la luz."},
    "c5-s5": {"D": ["¿Cómo sabría la placa que alguien ha cogido tu estuche? ¡Porque se mueve!", "Al agitar: un icono y una alarma.", "Botón A, alarma activada. Botón B, desactivada.", "La metemos en el estuche y la probamos."],
              "B": ["Una alarma sencilla: al agitar, suena."],
              "extra": "Que la alarma se desactive con un código: A, A, B."},
    "c5-s6": {"D": ["¡Cazabichos! Tres programas con un bicho cada uno: lamparita, contador y dado.", "Los copiamos, los probamos y los arreglamos.", "Después, el plan de nuestro invento: un sensor y una respuesta."],
              "extra": "Fabricad un bicho para otra pareja."},
    "c5-s7": {"D": ["Hoy construimos nuestro invento.", "Primero en el simulador; después en la placa.", "Lo probamos de verdad: ¿hay que ajustar el umbral?", "Se lo enseñamos a otra pareja."],
              "extra": "Una caja o carcasa de cartón para el invento."},
    "c5-s8": {"D": ["Encajamos la micro:bit en el robot Nezha.", "Botón A: motores en marcha durante 1 segundo.", "¿Cuánto avanza en 1 segundo? Lo medimos.", "Reto: llegar justo a una línea a 1 metro."],
              "extra": "Llegar a 1,5 metros calculando el tiempo."},
    "c5-s9": {"D": ["¿Cómo aprende una máquina? Probamos una que solo ha visto manzanas rojas.", "Jugamos a «¿Verdad, bulo o IA?».", "Escribimos 5 normas para no creernos bulos."],
              "extra": "Clasificad los bulos por tipos: foto trucada, titular falso, imagen hecha con IA."},
    "c5-s10": {"D": ["Diseñamos en 3D con Tinkercad.", "Movemos formas, cambiamos medidas y hacemos agujeros.", "Reto: un llavero de 40 × 20 × 4 mm con el nombre del equipo y un agujero para la anilla."],
               "extra": "El llavero con el borde redondeado."},
    "c5-s11": {"retos": ["Biblioteca silenciosa: una cara triste si hay mucho ruido.", "Semáforo de la fuente o del baño: libre u ocupado.", "Robot de reparto: el Nezha lleva una nota de una mesa a otra.", "Aviso de ventilación: si sube la temperatura, avisa de abrir la ventana."],
               "D": ["Cada equipo elige un reto y reparte las tareas.", "Construimos y programamos: un sensor y una acción.", "Al final, foto del montaje y tarjeta «Dónde lo dejamos»."],
               "extra": "Un segundo sensor o un registro de datos."},
    "c5-s12": {"D": ["Primero optimizamos: ¿algo repetido? ¿Algo que sobra? ¿Nombres claros?", "¡Feria del Código! Cada equipo cuenta el problema, la solución y cómo funciona."],
               "extra": "Presentad con un dato medido: distancia, temperatura o ruido."},
    "c5-s13": {"D": ["Leemos la tarjeta «Dónde lo dejamos».", "Programamos y probamos nuestro invento.", "Otro equipo lo prueba y busca bichos."],
               "extra": "Una mejora propia del equipo."},
    "c5-s14": {"D": ["El robot Nezha con un sensor.", "Que se pare antes de chocar con un obstáculo.", "Sin sensor: que arranque y pare con los botones."],
               "extra": "Que el robot esquive el obstáculo en lugar de pararse."},
    "c5-s15": {"D": ["Diseñamos en 3D un objeto útil: un soporte para lápices, un portanombres…", "Medimos el objeto real con la regla y usamos esas medidas."],
               "extra": "Un objeto con dos piezas que encajen."},
    "c5-s16": {"A": ["Dos placas que se mandan mensajes por radio.", "Cada equipo, su número de grupo: si otro lo usa, ¡lee nuestros mensajes!", "Reto: pulsar A en una placa y que salga un número en la otra."],
               "B": ["Diseñamos en 3D una funda para la micro:bit.", "Medimos la placa con la regla y sumamos la holgura y la pared.", "Caja Sólida, caja Hueca, Alinear y Agrupar."],
               "extra": "Un termómetro a distancia, o una tapa para la funda que encaje."},
    # ---------------------------------------------------------------- 6º
    "c6-s1": {"extra": "El reto 4 con un marcador de victorias."},
    "c6-s2": {"A": ["Programamos una mascota virtual.", "Botón A: come. Botón B: nos dice cuánta hambre tiene. Agitar: juega.", "Con el tiempo le entra hambre…", "Si tiene mucha hambre, se pone triste."],
              "B": ["Un mando con muchos eventos: botones, agitar, inclinar…", "Cada uno enseña una flecha o un icono distinto.", "Después, «Simón dice» con la placa."],
              "extra": "Que la mascota tenga hambre y también sueño."},
    "c6-s3": {"D": ["Medimos el colegio: temperatura y luz.", "Cada equipo mide en tres sitios y lo apunta.", "Juntamos los datos, calculamos la media y hacemos un gráfico.", "¿Dónde hace más calor? ¿Dónde hay más luz? ¿Por qué?"],
              "extra": "Comparad la media con el valor máximo y el mínimo."},
    "c6-s4": {"D": ["El robot Nezha: velocidad y tiempo.", "¿Cuánto avanza en 1 segundo? ¿Y en 2? ¿Y más rápido?", "Con velocidad negativa, el motor gira al revés.", "Reto: un cuadrado de 50 cm de lado con repetir."],
              "extra": "Un triángulo equilátero: ¿cuánto hay que girar?"},
    "c6-s5": {"A": ["Construimos un montaje con mecanismos.", "¿Qué pasa con la velocidad si cambiamos el tamaño del engranaje?"],
              "B": ["Un robot con sensor: que se pare antes de chocar o que siga una línea."],
              "C": ["Tres eventos, tres comportamientos: A arranca, B para y A+B gira."],
              "extra": "Combinad un mecanismo y un sensor."},
    "c6-s6": {"D": ["Optimizamos un programa largo: lo repetido, en un repetir o en una función.", "Nombres claros: ¿cuántos bloques antes y después?", "Después, el plan de nuestro proyecto: al menos un sensor y dos eventos."],
              "extra": "Una función con un número de entrada."},
    "c6-s7": {"D": ["Hoy construimos nuestro proyecto.", "Primero en el simulador; después en la placa o en el robot.", "Repasamos: ¿algo repetido? ¿Sobra algo? ¿Nombres claros?", "Se lo enseñamos a otra pareja."],
              "extra": "Añadid un tercer evento."},
    "c6-s8": {"A": ["¿Dónde hay inteligencia artificial en nuestra vida?", "Cada equipo estudia un caso y lo cuenta en un minuto.", "Escribimos 3 normas para usar la IA y las redes con responsabilidad."],
              "B": ["Dibujamos nuestra huella: qué dejaríamos en internet.", "¿Qué se queda? ¿Quién lo puede ver?"],
              "extra": "Escribid una norma nueva para la IA que crea textos e imágenes."},
    "c6-s9": {"D": ["Diseñamos en 3D un objeto que resuelva un problema.", "Medimos con regla el objeto real y usamos esas medidas en milímetros.", "Al final, una captura del diseño."],
              "extra": "Un objeto con una pieza que encaje en otra."},
    "c6-s10": {"D": ["Proyecto de servicio: ¿qué necesita nuestro colegio?", "Cada equipo elige una necesidad y planifica la solución.", "Regla de oro: un sensor, una acción, y que se pueda construir en una o dos sesiones."],
               "extra": "Calculad el material o el coste del prototipo."},
    "c6-s11": {"D": ["Construimos y programamos el prototipo.", "Cada uno con su tarea.", "Repasamos el programa: ¿se puede mejorar?", "Foto y tarjeta «Dónde lo dejamos»."],
               "extra": "Probad el prototipo con un usuario y apuntad los datos."},
    "c6-s12": {"D": ["Creamos el código QR de nuestro proyecto.", "¡Feria! Contamos el problema, la solución, cómo funciona y qué mejoraríamos.", "Y dejamos nuestro legado para los de 5º del curso que viene."],
               "extra": "Un gráfico con los datos de las pruebas en la presentación."},
    "c6-s13": {"D": ["Programamos el prototipo y lo probamos con usuarios de verdad.", "Lo mejoramos con lo que nos digan."],
               "extra": "Una mejora que propongan los usuarios."},
    "c6-s14": {"D": ["Una red de micro:bits: dos placas se hablan por radio.", "Cada equipo, su número de grupo: si otro lo usa, ¡lee nuestros mensajes!", "Retos: un timbre a distancia, un termómetro remoto o un mando por radio para el Nezha."],
               "extra": "Un termómetro que envíe la temperatura cada minuto."},
    "c6-s15": {"D": ["Diseñamos con bloques de código en Tinkercad, o una pieza que encaje en otra."],
               "extra": "Una fila de cilindros con un bucle."},
    "c6-s16": {"A": ["Diseñamos en 3D el soporte del cartel con nuestro código QR.", "Medimos el cartel y hacemos una ranura a su medida.", "¿Cabe el cartel? ¿Se cae la base?"],
               "B": ["Retos de lógica en la pizarra: cartas binarias y ordenar con la balanza.", "¿Con cuántas comparaciones se ordenan 8 cajas?"],
               "extra": "Un soporte que sujete el cartel inclinado."},
}
