# Datos de los pósteres de conceptos (M26) y del vocabulario por curso (M27 y apartado de cada curso).
# Una sola fuente: materiales.py genera los PDF y vocab_md.py escribe los apartados de los .md.

# (palabra, qué significa, sesión en que aparece)
VOCAB = {
    1: [
        ("instrucción", "Lo que le decimos al robot que haga, una cada vez.", "S1"),
        ("secuencia", "Instrucciones en orden, una detrás de otra.", "S2"),
        ("algoritmo", "Los pasos ordenados para conseguir algo.", "S2"),
        ("descomponer", "Partir una tarea grande en pasos pequeños.", "S3"),
        ("cuadrícula", "Tablero de casillas por donde se mueve el robot.", "S4"),
        ("programa", "Todas las instrucciones que sigue el robot.", "S4"),
        ("girar", "Dar un cuarto de vuelta a la derecha o a la izquierda, sin cambiar de casilla.", "S4"),
        ("patrón", "Algo que se repite siguiendo una regla.", "S5"),
        ("bicho", "Un error en el programa.", "S6"),
        ("depurar", "Encontrar el bicho y arreglarlo.", "S6"),
        ("entrada y salida", "Lo que le damos al robot (pulsar, una tarjeta) y lo que hace (moverse, sonar).", "S7"),
        ("repetir", "Hacer varias veces lo mismo con una sola orden.", "S9"),
        ("bloque", "Pieza de un programa, como las de ScratchJr.", "S10"),
        ("optimizar", "Conseguir lo mismo con menos tarjetas.", "S20"),
    ],
    2: [
        ("algoritmo", "Lista de pasos ordenados para conseguir algo.", "S2"),
        ("patrón que crece", "Un patrón en el que cada vez hay uno más (o dos más…).", "S3"),
        ("bucle", "Repetir un trozo del programa varias veces.", "S4"),
        ("condición", "Una regla del tipo «SI pasa esto, ENTONCES hago aquello».", "S9"),
        ("evento", "La señal que hace que un programa empiece: «CUANDO pasa algo…».", "S10"),
        ("árbol de preguntas", "Preguntas de sí o no que separan en grupos hasta encontrar la respuesta.", "S12"),
        ("clasificar", "Separar cosas en grupos según una regla.", "S13"),
        ("atributo", "Una característica: el color, la forma, el tamaño.", "S13"),
        ("proyecto", "Un trabajo que planificamos, hacemos, probamos y presentamos.", "S14"),
        ("bucle infinito", "Un bucle que no termina nunca («vuelve a la 5» desde la 5).", "S15"),
        ("optimizar", "Hacer lo mismo con menos instrucciones.", "S19"),
        ("personaje", "Cada figura que programamos en ScratchJr.", "S22"),
    ],
    3: [
        ("diagrama de flujo", "Dibujo de un algoritmo con formas y flechas.", "S2"),
        ("rombo", "En un diagrama, la forma de las preguntas de sí o no.", "S2"),
        ("polígono", "Figura plana con lados rectos: triángulo, cuadrado, hexágono…", "S3"),
        ("grado", "Lo que mide un giro. Una vuelta entera son 360 grados.", "S3"),
        ("si… si no", "Condición con dos caminos: si se cumple hago una cosa; si no, otra.", "S5"),
        ("datos", "Información que recogemos: votos, medidas, resultados.", "S7"),
        ("gráfico de barras", "Dibujo de los datos con barras: la más alta es la que más tiene.", "S7"),
        ("escenario y objeto", "En Scratch, el fondo donde pasa todo y cada personaje que programamos.", "S9"),
        ("disfraz", "Cada dibujo de un objeto de Scratch. Cambiarlo hace que se mueva.", "S11"),
        ("por siempre", "Bucle que no para hasta que paramos el programa.", "S11"),
        ("variable", "Una caja con nombre que guarda un número que puede cambiar.", "S13"),
        ("circuito", "Camino cerrado por el que pasa la electricidad.", "S17"),
        ("conductor y aislante", "Material por el que pasa la electricidad y material por el que no.", "S17"),
    ],
    4: [
        ("bucle anidado", "Un bucle dentro de otro bucle, como en el rosetón.", "S2"),
        ("número aleatorio", "Un número al azar que elige el ordenador.", "S5"),
        ("resto (mod)", "Lo que sobra al dividir. Si el resto entre 2 es 0, el número es par.", "S5"),
        ("coordenadas (x, y)", "Dos números que dicen dónde está algo en el escenario.", "S10"),
        ("¿tocando…?", "Pregunta de Scratch que comprueba si dos objetos se tocan.", "S11"),
        ("mensaje", "Aviso que un objeto envía y otros reciben para empezar a hacer algo.", "S13"),
        ("nivel", "Cada parte de un juego, más difícil que la anterior.", "S13"),
        ("playtesting", "Probar un juego con otras personas para mejorarlo.", "S14"),
        ("contrastar", "Comprobar una información en otra fuente fiable.", "S15"),
        ("bloque propio", "Un bloque que creamos nosotros para no repetir el mismo trozo.", "S21"),
        ("usuario", "La persona que va a usar lo que programamos.", "S22"),
        ("huella digital", "Lo que dejamos en internet y que otros pueden ver.", "S23"),
    ],
    5: [
        ("placa programable", "Un ordenador diminuto, como la micro:bit, que programamos con bloques.", "S2"),
        ("simulador", "La placa dibujada en la pantalla para probar antes de pasar a la de verdad.", "S2"),
        ("sensor", "Parte que mide algo del mundo: movimiento, luz, temperatura, sonido.", "S3"),
        ("acelerómetro", "Sensor que nota si la placa se mueve o se agita.", "S3"),
        ("umbral", "El número a partir del cual el programa decide («si luz < 50…»).", "S4"),
        ("activado y desactivado", "Dos estados que guarda una variable, como un interruptor.", "S5"),
        ("motor", "Pieza que hace girar las ruedas del robot.", "S8"),
        ("velocidad", "Cuánto avanza el robot en un tiempo.", "S8"),
        ("inteligencia artificial", "Programas que aprenden de muchos ejemplos.", "S9"),
        ("sesgo", "Error que aparece cuando los ejemplos no son variados.", "S9"),
        ("bulo", "Una información falsa que se difunde como si fuera verdad.", "S9"),
        ("diseño 3D", "Dibujo de un objeto con alto, ancho y fondo.", "S10"),
        ("prototipo", "Primera versión de un invento, para probarla y mejorarla.", "S11"),
    ],
    6: [
        ("milisegundo", "La milésima parte de un segundo: 1000 ms = 1 s.", "S1"),
        ("estado", "Cómo está algo en cada momento, guardado en una variable (hambre, activado).", "S2"),
        ("eventos múltiples", "Un programa que responde a varias señales distintas.", "S2"),
        ("media", "Reparto a partes iguales: se suman los datos y se divide entre cuántos hay.", "S3"),
        ("hoja de cálculo", "Programa de tablas que calcula y hace gráficos.", "S3"),
        ("polaridad", "El sentido de la corriente. Cambiarla hace que el motor gire al revés.", "S4"),
        ("función", "Un trozo de programa con nombre que se puede usar muchas veces.", "S6"),
        ("IA generativa", "Inteligencia artificial que crea textos o imágenes nuevos.", "S8"),
        ("privacidad", "Decidir qué información mía ven los demás.", "S8"),
        ("escala", "Relación entre la medida de un dibujo y la real.", "S9"),
        ("proyecto de servicio", "Un proyecto que resuelve una necesidad real del colegio.", "S10"),
        ("radio", "Forma de enviar mensajes sin cables entre placas del mismo grupo.", "S14"),
    ],
}

# Pósteres: (clave, título, definición, frase clave, [(ciclo, ejemplo)], dónde colgarlo)
POSTERS = [
    ("algoritmo", "ALGORITMO", "Una lista de pasos, en orden, para conseguir algo.", "Un robot no adivina: hace lo que le dices.",
     [("1º y 2º", "Las tarjetas de flechas para llegar al tesoro."), ("3º y 4º", "Un programa de Scratch se lee de arriba abajo."),
      ("5º y 6º", "El programa de la micro:bit, paso a paso.")], "1º S1-S2 · 2º S2"),
    ("descomponer", "DESCOMPONER", "Partir un problema grande en partes pequeñas.", "Paso a paso, todo es más fácil.",
     [("1º y 2º", "Lavarse los dientes: cepillo, pasta, cepillar, enjuagar."), ("3º y 4º", "El videojuego: personaje, premio, enemigo, puntos y final."),
      ("5º y 6º", "El invento: sensor, respuesta, montaje y pruebas.")], "1º S3 · 4º S9"),
    ("patron", "PATRÓN", "Algo que se repite siguiendo una regla. Si descubro la regla, sé lo que viene.", "Busca lo que se repite.",
     [("1º y 2º", "Rojo, azul, rojo, azul… ¿qué viene ahora?"), ("3º y 4º", "Polígonos: el giro es siempre 360 ÷ lados."),
      ("5º y 6º", "Una función: el mismo trozo sirve para muchos casos.")], "1º S5 · 2º S3"),
    ("bucle", "BUCLE", "Repetir varias veces lo mismo sin escribirlo cada vez.", "Menos tarjetas, mismo camino.",
     [("1º y 2º", "La tarjeta REPITE ×3."), ("3º y 4º", "Los bloques «repetir 4» y «por siempre»."),
      ("5º y 6º", "«para siempre» en la micro:bit; un bucle dentro de otro.")], "1º S9 · 2º S4"),
    ("condicion", "CONDICIÓN", "Una pregunta que decide: SI pasa esto, ENTONCES hago aquello; SI NO, hago otra cosa.", "Si se cumple… si no…",
     [("1º y 2º", "SI llueve, ENTONCES cojo el paraguas."), ("3º y 4º", "si ¿tocando manzana? entonces sumar 1 a puntos."),
      ("5º y 6º", "si nivel de luz < 50 entonces encender las luces.")], "2º S9 · 3º S5"),
    ("evento", "EVENTO", "La señal que hace que un programa empiece: CUANDO pasa algo…", "Cada programa espera su señal.",
     [("1º y 2º", "CUANDO aplaudo, brazos arriba."), ("3º y 4º", "«al presionar tecla», «al recibir mensaje»."),
      ("5º y 6º", "«al presionar el botón A», «al agitar».")], "2º S10 · 3º S9"),
    ("variable", "VARIABLE", "Una caja con nombre que guarda un número que puede cambiar.", "La caja se llama igual; lo de dentro cambia.",
     [("1º y 2º", "Los puntos que llevo en un juego de mesa."), ("3º y 4º", "puntos y vidas en Scratch."),
      ("5º y 6º", "El hambre de la mascota virtual; un contador de pasos.")], "3º S13 · 4º S4"),
    ("depurar", "DEPURAR", "Buscar el error (el «bicho») y arreglarlo. Equivocarse es parte de programar.", "¿Qué quería que pasara y qué ha pasado?",
     [("1º y 2º", "Seguir las flechas con el dedo y rodear la que falla."), ("3º y 4º", "Ir paso a paso: ¿en qué bloque empieza a fallar?"),
      ("5º y 6º", "Probar con el sensor y ajustar el umbral.")], "1º S6 · todos los cursos"),
    ("entradasalida", "ENTRADA Y SALIDA", "Algo entra (lo que pulsamos o mide un sensor), el programa decide y algo sale (lo que hace la máquina).", "Algo entra, el programa decide, algo sale.",
     [("1º y 2º", "Pulso un botón de Tale-Bot y el robot avanza."), ("3º y 4º", "Toco el aluminio del Makey Makey y suena una nota."),
      ("5º y 6º", "El sensor mide poca luz y se encienden los LED.")], "1º S7 · 3º S17 · 5º S2"),
    ("optimizar", "OPTIMIZAR", "Conseguir lo mismo con menos pasos o de forma más clara.", "¿Se podría hacer con menos pasos?",
     [("1º y 2º", "Juntar tarjetas iguales con REPITE."), ("3º y 4º", "Quitar bloques que sobran y ordenar el programa."),
      ("5º y 6º", "Funciones y nombres claros.")], "1º S20 · 2º S19 · 3º S22"),
]
